"""
Configurazione strumenti e parametri di default.
Modifica gli indirizzi VISA in base alla tua rete.
"""

# ── Strumenti ─────────────────────────────────────────────
#IF2 Noise Floor +20dbm
INSTRUMENTS = {
    "DSA1030_1": {
        "visa_address": "TCPIP0::192.168.60.69::INSTR",
        "label": "IF1",
    },
    "DSA1030_2": {
        "visa_address": "TCPIP0::192.168.60.70::INSTR",
        "label": "IF2",
    },
}
# ── Autenticazione serv ───────────────────────────────────
SERV_HOST = "192.168.51.14"
SERVPORT = 5002
# ── Autenticazione operatore ──────────────────────────────
OPERATOR_PASSWORD = "medicina"
# Chiave segreta per cifrare i cookie di sessione NiceGUI
STORAGE_SECRET = "5bdbbe01b9a2d482e9dd963742df8ad3d756999ea104bda01b336f25599410a6"

# ── Parametri VISA ────────────────────────────────────────
VISA_TIMEOUT_MS = 10_000  # timeout lettura/scrittura

# ── Parametri UI ──────────────────────────────────────────
TRACE_UPDATE_INTERVAL_S = 1.0  # polling traccia (secondi)
RECORDINGS_DIR = "recordings"  # directory per i file di registrazione

# ___ Lista Assi Subriflettore ______________________________
SUB_AXES = ["X", "Y", "Z1", "Z2", "Z3"]

# ── Posizione osservatorio ─────────────────────────────────
# Stazione Radioastronomica di Medicina (BO)
MEDICINA_LONGITUDE_DEG = 11.6450  # gradi Est

# ── Valori di default per i controlli ─────────────────────
DEFAULT_CENTER_FREQ_HZ = 1.5e9       # 1.5 GHz
DEFAULT_SPAN_HZ = 1.0e9              # 1 GHz
DEFAULT_RBW_HZ = 100e3               # 100 kHz
DEFAULT_VBW_HZ = 100e3               # 100 kHz


# ── Range DSA1030 ─────────────────────────────────────────
FREQ_MIN_HZ = 9e3          # 9 kHz
FREQ_MAX_HZ = 3.0e9        # 3 GHz
RBW_OPTIONS_HZ = [
    10, 30, 100, 300,
    1e3, 3e3, 10e3, 30e3, 100e3, 300e3,
    1e6,
]
VBW_OPTIONS_HZ = RBW_OPTIONS_HZ.copy()

# ── Altri parametri ───────────────────────────────────────
MAX_POINTS = 3001  # numero massimo di punti per traccia

"""
Comandi SCPI per Rigol DSA1000 Series.
Auto-generato dal Programming Guide.

Include varianti con e senza prefissi opzionali (es. [:SENSe]).
Totale: 979 comandi.
"""

SCPI_COMMANDS: dict[str, str] = {
    "*CLS": "Clear all the event registers and the error queue.",
    "*ESE": "*ESE <value> is used to set the enable register for the standard event status register.",
    "*ESE?": "*ESE <value> is used to set the enable register for the standard event status register.",
    "*ESR?": "Query and clear the event register for the standard event status register.",
    "*IDN?": "Query and return the ID character string of the instrument.",
    "*OPC": "*OPC: sets the “Operation Complete” (bit 0) of the standard event status register to 1 after the current operation.",
    "*OPC?": "*OPC: sets the “Operation Complete” (bit 0) of the standard event status register to 1 after the current operation.",
    "*RST": "Reset the analyzer to the default state.",
    "*SRE": "*SRE <value> is used to set the enable register for the status byte register.",
    "*SRE?": "*SRE <value> is used to set the enable register for the status byte register.",
    "*STB?": "Query the event register for the status byte register.",
    "*TRG": "Trigger a sweep or measurement immediately.",
    "*WAI": "Wait for the operation to finish.",
    ":ABORt": "Give up the current operation and sweep all over again.",
    ":ACPower:AVERage": "Turn on or off the Average function of the adjacent channel power measurement.",
    ":ACPower:AVERage:COUNt": "Specify the number of averages on the adjacent channel power measurement results.",
    ":ACPower:AVERage:COUNt?": "Specify the number of averages on the adjacent channel power measurement results.",
    ":ACPower:AVERage:TCONtrol": "Set the average mode of the adjacent channel power measurement to exponential or repeat.",
    ":ACPower:AVERage:TCONtrol?": "Set the average mode of the adjacent channel power measurement to exponential or repeat.",
    ":ACPower:AVERage?": "Turn on or off the Average function of the adjacent channel power measurement.",
    ":ACPower:BANDwidth:ACHannel": "Set the bandwidth of the adjacent channel and the default unit is Hz.",
    ":ACPower:BANDwidth:ACHannel?": "Set the bandwidth of the adjacent channel and the default unit is Hz.",
    ":ACPower:BANDwidth:INTegration": "Set the bandwidth of the main channel and the default unit is Hz.",
    ":ACPower:BANDwidth:INTegration?": "Set the bandwidth of the main channel and the default unit is Hz.",
    ":ACPower:CSPacing": "Set the center frequency difference between the main and adjacent channels and the default unit is Hz.",
    ":ACPower:CSPacing?": "Set the center frequency difference between the main and adjacent channels and the default unit is Hz.",
    ":BANDwidth:EMIFilter:STATe": "Enable or disable the EMI filter.",
    ":BANDwidth:EMIFilter:STATe?": "Enable or disable the EMI filter.",
    ":BANDwidth:RESolution": "Set the resolution bandwidth and the default unit is Hz.",
    ":BANDwidth:RESolution:AUTO": "Enable or disable the Auto setting mode of resolution bandwidth.",
    ":BANDwidth:RESolution:AUTO?": "Enable or disable the Auto setting mode of resolution bandwidth.",
    ":BANDwidth:RESolution?": "Set the resolution bandwidth and the default unit is Hz.",
    ":BANDwidth:VIDeo": "Set the video bandwidth and the default unit is Hz.",
    ":BANDwidth:VIDeo:AUTO": "Enable or disable the Auto setting mode of video bandwidth.",
    ":BANDwidth:VIDeo:AUTO?": "Enable or disable the Auto setting mode of video bandwidth.",
    ":BANDwidth:VIDeo:RATio": "Set the ratio of VBW to RBW.",
    ":BANDwidth:VIDeo:RATio?": "Set the ratio of VBW to RBW.",
    ":BANDwidth:VIDeo?": "Set the video bandwidth and the default unit is Hz.",
    ":CALCulate:BANDwidth:NDB": "Set the value of N of the N dB BW measurement.",
    ":CALCulate:BANDwidth:NDB?": "Set the value of N of the N dB BW measurement.",
    ":CALCulate:BANDwidth:RESult?": "The query returns the measured bandwidth (in Hz) according to the N value specified by the :CALCulate:BANDwidth:NDB c...",
    ":CALCulate:LLINe:ALL:DELete": "Delete the current edited limit line.",
    ":CALCulate:LLINe:CONTrol:DOMain": "Set the unit of X axis to frequency or time unit.",
    ":CALCulate:LLINe:CONTrol:DOMain?": "Set the unit of X axis to frequency or time unit.",
    ":CALCulate:LLINe:FAIL:RATIo?": "The query returns the failure ratio of the pass/fail test results in scientific notation.",
    ":CALCulate:LLINe:FAIL:STOP:STATe": "Set whether to start a new sweep if the test fails.",
    ":CALCulate:LLINe:FAIL:STOP:STATe?": "Set whether to start a new sweep if the test fails.",
    ":CALCulate:LLINe:FAIL?": "Query the Pass/Fail test result.",
    ":CALCulate:LLINe<n>:CONTrol:INTerpolate:TYPE": "Set the type of frequency interpolation to log or linear.",
    ":CALCulate:LLINe<n>:DATA": "Create a limit line.",
    ":CALCulate:LLINe<n>:DATA:MERGe": "Add extra points to the limit line.",
    ":CALCulate:LLINe<n>:DELete": "Delete the limit line you are editing.",
    ":CALCulate:LLINe<n>:STATe": "Turn on or off the upper/lower limit line.",
    ":CALCulate:LLINe<n>:STATe?": "Turn on or off the upper/lower limit line.",
    ":CALCulate:MARKer:AOFF": "Turn off all the markers enabled and all the functions based upon markers.",
    ":CALCulate:MARKer:FCOunt": "Turn on or off the frequency counter.",
    ":CALCulate:MARKer:FCOunt:RESolution": "Set the frequency counter resolution and the default unit is Hz.",
    ":CALCulate:MARKer:FCOunt:RESolution:AUTO": "Set the resolution mode of frequency counter to Auto to relate it to the span to get accurate counting as fast as possible.",
    ":CALCulate:MARKer:FCOunt:RESolution?": "Set the frequency counter resolution and the default unit is Hz.",
    ":CALCulate:MARKer:FCOunt:STATe": "Turn on or off the frequency counter.",
    ":CALCulate:MARKer:FCOunt:STATe?": "Turn on or off the frequency counter.",
    ":CALCulate:MARKer:FCOunt:X?": "The query returns the readout of the frequency counter, for example, 1500335500 (in Hz).",
    ":CALCulate:MARKer:FCOunt?": "Turn on or off the frequency counter.",
    ":CALCulate:MARKer:FCOunt[:STATe]": "Turn on or off the frequency counter.",
    ":CALCulate:MARKer:FCOunt[:STATe]?": "Turn on or off the frequency counter.",
    ":CALCulate:MARKer:TABLe:STATe": "Turn on or off the marker table.",
    ":CALCulate:MARKer:TABLe:STATe?": "Turn on or off the marker table.",
    ":CALCulate:MARKer:TRACking": "Turn on or off the signal track function.",
    ":CALCulate:MARKer:TRACking:STATe": "Turn on or off the signal track function.",
    ":CALCulate:MARKer:TRACking:STATe?": "Turn on or off the signal track function.",
    ":CALCulate:MARKer:TRACking?": "Turn on or off the signal track function.",
    ":CALCulate:MARKer:TRACking[:STATe]": "Turn on or off the signal track function.",
    ":CALCulate:MARKer:TRACking[:STATe]?": "Turn on or off the signal track function.",
    ":CALCulate:MARKer<n>:CENTer": "Set the center frequency of the analyzer based upon the curren marker frequency.",
    ":CALCulate:MARKer<n>:CPEak": "Turn on or off the continuous peak search.",
    ":CALCulate:MARKer<n>:CPEak:STATe": "Turn on or off the continuous peak search.",
    ":CALCulate:MARKer<n>:CPEak:STATe?": "Turn on or off the continuous peak search.",
    ":CALCulate:MARKer<n>:CPEak?": "Turn on or off the continuous peak search.",
    ":CALCulate:MARKer<n>:CPEak[:STATe]": "Turn on or off the continuous peak search.",
    ":CALCulate:MARKer<n>:CPEak[:STATe]?": "Turn on or off the continuous peak search.",
    ":CALCulate:MARKer<n>:DELTa:CENTer": "Set the center frequency to the frequency difference between the two markers in “Delta”, “Delta Pair” or “Span Pair” ...",
    ":CALCulate:MARKer<n>:DELTa:SET:CENTer": "Set the center frequency to the frequency difference between the two markers in “Delta”, “Delta Pair” or “Span Pair” ...",
    ":CALCulate:MARKer<n>:DELTa:SET:SPAN": "Set the analyzer span to the frequency difference between the two markers in “Delta”, “Delta Pair” and “Span Pair” ma...",
    ":CALCulate:MARKer<n>:DELTa:SPAN": "Set the analyzer span to the frequency difference between the two markers in “Delta”, “Delta Pair” and “Span Pair” ma...",
    ":CALCulate:MARKer<n>:DELTa[:SET]:CENTer": "Set the center frequency to the frequency difference between the two markers in “Delta”, “Delta Pair” or “Span Pair” ...",
    ":CALCulate:MARKer<n>:DELTa[:SET]:SPAN": "Set the analyzer span to the frequency difference between the two markers in “Delta”, “Delta Pair” and “Span Pair” ma...",
    ":CALCulate:MARKer<n>:FUNCtion": "Set the measurement type of MarkFctn for the specified marker.",
    ":CALCulate:MARKer<n>:FUNCtion?": "Set the measurement type of MarkFctn for the specified marker.",
    ":CALCulate:MARKer<n>:MAXimum:LEFT": "Search and mark the nearest peak which is located at the left side of the current peak on the trace and meets the pea...",
    ":CALCulate:MARKer<n>:MAXimum:MAX": "Execute a peak search according to the mode selected by the :CALCulate:MARKer<n>:PEAK:SEARch:MODE command.",
    ":CALCulate:MARKer<n>:MAXimum:NEXT": "Search and mark the peak whose amplitude is closest to that of the current peak and which meets the peak search condi...",
    ":CALCulate:MARKer<n>:MAXimum:RIGHt": "Search and mark the nearest peak which is located at the right side of the current peak on the trace and meets the pe...",
    ":CALCulate:MARKer<n>:MINimum": "Search and mark the peak with the minimum amplitude on the trace.",
    ":CALCulate:MARKer<n>:MODE": "Set the type of the selected marker.",
    ":CALCulate:MARKer<n>:MODE?": "Set the type of the selected marker.",
    ":CALCulate:MARKer<n>:PEAK:CF": "Execut a peak search and set the center frequency of the analyzer to the frequency of the current peak.",
    ":CALCulate:MARKer<n>:PEAK:EXCursion": "Set the excursion between the specified peak and the minimum amplitude on both sides of it in dB.",
    ":CALCulate:MARKer<n>:PEAK:SEARch:MODE": "Set the mode of Peak Search.",
    ":CALCulate:MARKer<n>:PEAK:SET:CF": "Execut a peak search and set the center frequency of the analyzer to the frequency of the current peak.",
    ":CALCulate:MARKer<n>:PEAK:THReshold": "Set the peak threshold and the default unit is dBm.",
    ":CALCulate:MARKer<n>:PEAK:THReshold?": "Set the peak threshold and the default unit is dBm.",
    ":CALCulate:MARKer<n>:PEAK[:SET]:CF": "Execut a peak search and set the center frequency of the analyzer to the frequency of the current peak.",
    ":CALCulate:MARKer<n>:PTPeak": "Execut peak-peak search.",
    ":CALCulate:MARKer<n>:RLEVel": "Set the reference level of the analyzer according to the current marker amplitude.",
    ":CALCulate:MARKer<n>:SET:CENTer": "Set the center frequency of the analyzer based upon the curren marker frequency.",
    ":CALCulate:MARKer<n>:SET:RLEVel": "Set the reference level of the analyzer according to the current marker amplitude.",
    ":CALCulate:MARKer<n>:SET:STARt": "Set the start frequency of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>:SET:STEP": "Set the center frequency step of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>:SET:STOP": "Set the stop frequency of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>:STARt": "Set the start frequency of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>:STATe": "Turn on or off the selected marker.",
    ":CALCulate:MARKer<n>:STATe?": "Turn on or off the selected marker.",
    ":CALCulate:MARKer<n>:STEP": "Set the center frequency step of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>:STOP": "Set the stop frequency of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>:TRACe": "Assign a trace for the specified marker from Trace 1, Trace 2, Trace 3 or Trace 4 (math trace).",
    ":CALCulate:MARKer<n>:TRACe:AUTO": "Turn on or off the auto trace function for the specified marker.",
    ":CALCulate:MARKer<n>:TRACe:AUTO?": "Turn on or off the auto trace function for the specified marker.",
    ":CALCulate:MARKer<n>:TRACe?": "Assign a trace for the specified marker from Trace 1, Trace 2, Trace 3 or Trace 4 (math trace).",
    ":CALCulate:MARKer<n>:X": "Set the X-axis value of the marker and the default unit is Hz.",
    ":CALCulate:MARKer<n>:X:CENTer": "Set the X value at the center of the reference marker and the delta marker in “Span Pair” marker mode and the default unit is Hz.",
    ":CALCulate:MARKer<n>:X:CENTer?": "Set the X value at the center of the reference marker and the delta marker in “Span Pair” marker mode and the default unit is Hz.",
    ":CALCulate:MARKer<n>:X:POSition": "Set the position of the point marked by the “Normal” marker.",
    ":CALCulate:MARKer<n>:X:POSition:CENTer": "Set the position of the center frequency of “Span Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition:CENTer?": "Set the position of the center frequency of “Span Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition:SPAN": "Set the number of points corresponding to the span of the “Span Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition:SPAN?": "Set the number of points corresponding to the span of the “Span Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition:STARt": "Set the position of the point marked by the reference marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition:STARt?": "Set the position of the point marked by the reference marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition:STOP": "Set the position of the point marked by the delta marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition:STOP?": "Set the position of the point marked by the delta marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X:POSition?": "Set the position of the point marked by the “Normal” marker.",
    ":CALCulate:MARKer<n>:X:READout": "Set the marker readout type on X axis.",
    ":CALCulate:MARKer<n>:X:SPAN": "Sets the X value corresponding to the span of the “Span Pair” marker.",
    ":CALCulate:MARKer<n>:X:SPAN?": "Sets the X value corresponding to the span of the “Span Pair” marker.",
    ":CALCulate:MARKer<n>:X:STARt": "Set the X value of the reference marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X:STARt?": "Set the X value of the reference marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X:STOP": "Set the X value of the delta marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X:STOP?": "Set the X value of the delta marker of the “Delta Pair” marker.",
    ":CALCulate:MARKer<n>:X?": "Set the X-axis value of the marker and the default unit is Hz.",
    ":CALCulate:MARKer<n>:Y?": "The query returns the Y-axis readout of the specified marker and the default unit is dBm.",
    ":CALCulate:MARKer<n>[:SET]:CENTer": "Set the center frequency of the analyzer based upon the curren marker frequency.",
    ":CALCulate:MARKer<n>[:SET]:RLEVel": "Set the reference level of the analyzer according to the current marker amplitude.",
    ":CALCulate:MARKer<n>[:SET]:STARt": "Set the start frequency of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>[:SET]:STEP": "Set the center frequency step of the analyzer according to the current marker frequency.",
    ":CALCulate:MARKer<n>[:SET]:STOP": "Set the stop frequency of the analyzer according to the current marker frequency.",
    ":CALCulate:NTData": "Turn on or off the Normalization function.",
    ":CALCulate:NTData:STATe": "Turn on or off the Normalization function.",
    ":CALCulate:NTData:STATe?": "Turn on or off the Normalization function.",
    ":CALCulate:NTData?": "Turn on or off the Normalization function.",
    ":CALCulate:NTData[:STATe]": "Turn on or off the Normalization function.",
    ":CALCulate:NTData[:STATe]?": "Turn on or off the Normalization function.",
    ":CALibration:ALL": "Calibrate immediately.",
    ":CALibration:AUTO": "Enable or disable the Auto calibration.",
    ":CALibration:AUTO?": "Enable or disable the Auto calibration.",
    ":CALibration[:ALL]": "Calibrate immediately.",
    ":CHPower:AVERage": "Turn on or off the average function of the channel power measurement.",
    ":CHPower:AVERage:COUNt": "Set the number of averages on the channel power measurement results.",
    ":CHPower:AVERage:COUNt?": "Set the number of averages on the channel power measurement results.",
    ":CHPower:AVERage:TCONtrol": "Set the average mode of the channel power measurement to exponential or repeat.",
    ":CHPower:AVERage:TCONtrol?": "Set the average mode of the channel power measurement to exponential or repeat.",
    ":CHPower:AVERage?": "Turn on or off the average function of the channel power measurement.",
    ":CHPower:BANDwidth:INTegration": "Set the integration bandwidth for the channel power measurement and the default unit is Hz.",
    ":CHPower:BANDwidth:INTegration?": "Set the integration bandwidth for the channel power measurement and the default unit is Hz.",
    ":CHPower:FREQuency:SPAN": "Set the channel span for the channel power measurement and the default unit is Hz.",
    ":CHPower:FREQuency:SPAN?": "Set the channel span for the channel power measurement and the default unit is Hz.",
    ":CNRatio:AVERage": "Turn on or off the average function of the C/N Ratio measurement.",
    ":CNRatio:AVERage:COUNt": "Set the number of averages on the C/N Ratio measurement results.",
    ":CNRatio:AVERage:COUNt?": "Set the number of averages on the C/N Ratio measurement results.",
    ":CNRatio:AVERage:TCONtrol": "Set the average mode of the C/N Ratio measurement to exponential or repeat.",
    ":CNRatio:AVERage:TCONtrol?": "Set the average mode of the C/N Ratio measurement to exponential or repeat.",
    ":CNRatio:AVERage?": "Turn on or off the average function of the C/N Ratio measurement.",
    ":CNRatio:BANDwidth:INTegration": "Set the carrier bandwidth and the default unit is Hz.",
    ":CNRatio:BANDwidth:INTegration?": "Set the carrier bandwidth and the default unit is Hz.",
    ":CNRatio:BANDwidth:NOISe": "Set the noise bandwidth and the default unit is Hz.",
    ":CNRatio:BANDwidth:NOISe?": "Set the noise bandwidth and the default unit is Hz.",
    ":CNRatio:OFFSet": "Set the center frequency difference between the carrier and noise and the default unit is Hz.",
    ":CNRatio:OFFSet?": "Set the center frequency difference between the carrier and noise and the default unit is Hz.",
    ":CONFigure:ACPower": "Enable the Adjacent Channel Power measurement.",
    ":CONFigure:CHPower": "Enable the Channel Power measurement.",
    ":CONFigure:CNRatio": "Enable the C/N Ratio measurement.",
    ":CONFigure:EBWidth": "Enable the Emission BandWidth measurement.",
    ":CONFigure:HDISt": "Enable the Harmonic Distortion measurement.",
    ":CONFigure:OBWidth": "Enable the Occupied BandWidth measurement.",
    ":CONFigure:PF": "Enable the Pass/Fail measurement.",
    ":CONFigure:SANalyzer": "Disable the current measurement and enable the Sweep mode of the anlyzer.",
    ":CONFigure:TOI": "Enable the Third Order Intermodulation measurement.",
    ":CONFigure:TPOWer": "Enable the Time-domain Power measurement.",
    ":CONFigure?": "Query the current measurement.",
    ":CORRection:CSET:ALL": "Enable or disable the amplitude correction function.",
    ":CORRection:CSET:ALL:DELete": "Delete all the amplitude correction data.",
    ":CORRection:CSET:ALL?": "Enable or disable the amplitude correction function.",
    ":CORRection:CSET:TABLe:STATe": "Turn on or off the correction table.",
    ":CORRection:CSET:TABLe:STATe?": "Turn on or off the correction table.",
    ":CORRection:CSET<n>": "Turn on or off the specified amplitude correction.",
    ":CORRection:CSET<n>:DATA": "Create an amplitude correction curve on the basis of the current data.",
    ":CORRection:CSET<n>:DATA:MERGe": "Add new correction data upon the current correction curve.",
    ":CORRection:CSET<n>:DELete": "Delete the correction settings.",
    ":CORRection:CSET<n>:X:SPACing": "Set the amplitude correction mode to Lin or Log.",
    ":CORRection:CSET<n>:X:SPACing?": "Set the amplitude correction mode to Lin or Log.",
    ":CORRection:CSET<n>?": "Turn on or off the specified amplitude correction.",
    ":COUPle": "Sets all the related parameters automatically on the basis of their coupling relations.",
    ":COUPle?": "Sets all the related parameters automatically on the basis of their coupling relations.",
    ":DEMod:STATe": "Turn on or off the demodulation.",
    ":DEMod:STATe?": "Turn on or off the demodulation.",
    ":DEMod:TIME": "Set the demodulating time and the default unit is s.",
    ":DEMod:TIME?": "Set the demodulating time and the default unit is s.",
    ":DISPlay:AFUnction:POSition": "Set the position of active function area.",
    ":DISPlay:AFUnction:POSition?": "Set the position of active function area.",
    ":DISPlay:ANNotation:CLOCk": "Set the clock status.",
    ":DISPlay:ANNotation:CLOCk:STATe": "Set the clock status.",
    ":DISPlay:ANNotation:CLOCk:STATe?": "Set the clock status.",
    ":DISPlay:ANNotation:CLOCk?": "Set the clock status.",
    ":DISPlay:ANNotation:CLOCk[:STATe]": "Set the clock status.",
    ":DISPlay:ANNotation:CLOCk[:STATe]?": "Set the clock status.",
    ":DISPlay:BRIGhtness": "Set the screen brightness.",
    ":DISPlay:BRIGhtness?": "Set the screen brightness.",
    ":DISPlay:ENABle": "Enable or disable the screen display.",
    ":DISPlay:ENABle?": "Enable or disable the screen display.",
    ":DISPlay:MENU:HTIMe": "Set the menu hold time.",
    ":DISPlay:MENU:HTIMe?": "Set the menu hold time.",
    ":DISPlay:MENU:STATe": "Turn on or off the menu hold function.",
    ":DISPlay:MENU:STATe?": "Turn on or off the menu hold function.",
    ":DISPlay:MSGswitch:STATe": "Enable or disable the message display.",
    ":DISPlay:MSGswitch:STATe?": "Enable or disable the message display.",
    ":DISPlay:SKIN": "Specify the screen skin.",
    ":DISPlay:SKIN?": "Specify the screen skin.",
    ":DISPlay:SSAVer:TIME": "Set the screen saver duration.",
    ":DISPlay:SSAVer:TIME?": "Set the screen saver duration.",
    ":DISPlay:WINdow:TRACe:GRATicule:GRID": "Set the grid brightness.",
    ":DISPlay:WINdow:TRACe:GRATicule:GRID?": "Set the grid brightness.",
    ":DISPlay:WINdow:TRACe:Y:DLINe": "Set the screen display line and the default unit is dBm.",
    ":DISPlay:WINdow:TRACe:Y:DLINe:STATe": "Enable or disable the display line.",
    ":DISPlay:WINdow:TRACe:Y:DLINe:STATe?": "Enable or disable the display line.",
    ":DISPlay:WINdow:TRACe:Y:DLINe?": "Set the screen display line and the default unit is dBm.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:NRLevel": "Set the reference level of the normalization.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:NRLevel?": "Set the reference level of the normalization.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:NRPosition": "Set the reference position of the normalization.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:NRPosition?": "Set the reference position of the normalization.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:PDIVision": "Specify the scale magnitude of Y axis.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:PDIVision?": "Specify the scale magnitude of Y axis.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:RLEVel": "Set the reference level.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:RLEVel:OFFSet": "Set the reference level offset.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:RLEVel:OFFSet?": "Set the reference level offset.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:RLEVel?": "Set the reference level.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:SPACing": "Set the scale type.",
    ":DISPlay:WINdow:TRACe:Y:SCALe:SPACing?": "Set the scale type.",
    ":EBWidth:AVERage": "Turn on or off the average function of the Emission Bandwidth",
    ":EBWidth:AVERage:COUNt": "Set the number of averages of the Emission Bandwidth measurement results.",
    ":EBWidth:AVERage:COUNt?": "Set the number of averages of the Emission Bandwidth measurement results.",
    ":EBWidth:AVERage:TCONtrol": "Set the average mode of the Emission Bandwidth measurement to exponential or repeat.",
    ":EBWidth:AVERage:TCONtrol?": "Set the average mode of the Emission Bandwidth measurement to exponential or repeat.",
    ":EBWidth:AVERage?": "Turn on or off the average function of the Emission Bandwidth",
    ":EBWidth:FREQuency:SPAN": "Set the span of the Emission Bandwidth measurement and the default unit is Hz.",
    ":EBWidth:FREQuency:SPAN?": "Set the span of the Emission Bandwidth measurement and the default unit is Hz.",
    ":EBWidth:MAXHold:STATe": "Turn on or off the Max Hold function.",
    ":EBWidth:MAXHold:STATe?": "Turn on or off the Max Hold function.",
    ":EBWidth:XDB": "Set the value of X dB of the emission bandwidth.",
    ":EBWidth:XDB?": "Set the value of X dB of the emission bandwidth.",
    ":FETCh:ACPower:LOWer?": "The query returns the lower channel power.",
    ":FETCh:ACPower:MAIN?": "The query returns the main channel power.",
    ":FETCh:ACPower:UPPer?": "The query returns upper channel power.",
    ":FETCh:ACPower?": "The query returns 5 values separated by commas: Main channel power Upper channel power, Power difference between uppe...",
    ":FETCh:CHPower:CHPower?": "The query returns the channel power.",
    ":FETCh:CHPower:DENSity?": "The query returns the channel power spectral density.",
    ":FETCh:CHPower?": "The query returns 2 values separated by commas: channel power and power spectral density.",
    ":FETCh:CNRatio:CARRier?": "The query returns the carrier power.",
    ":FETCh:CNRatio:CNRatio?": "The query returns the C/N Ratio in dB.",
    ":FETCh:CNRatio:NOISe?": "The query returns the noise power.",
    ":FETCh:CNRatio?": "The query returns 3 values separated by commas: carrier power, noise power and carrier-to-noise ratio (dB).",
    ":FETCh:EBWidth?": "The query returns the measurement result of emission bandwidth in Hz.",
    ":FETCh:HARMonics:AMPLitude:ALL?": "The query returns the amplitude values of the first ten harmonics separated by commas in the same unit of the current...",
    ":FETCh:HARMonics:AMPLitude?": "The query returns the specified harmonic amplitude.",
    ":FETCh:HARMonics:DISTortion?": "The query returns the percentage of THD (total harmonic",
    ":FETCh:HARMonics:FREQuency:ALL?": "The query returns the frequencies of first 10 harmonics separated by commas in Hz.",
    ":FETCh:HARMonics:FREQuency?": "Query the frequency of the specified harmonic in Hz.",
    ":FETCh:HARMonics:FUNDamental?": "The query returns the fundamental wave frequency in Hz.",
    ":FETCh:HARMonics?": "The query returns the percentage of THD (total harmonic",
    ":FETCh:HARMonics[:DISTortion]?": "The query returns the percentage of THD (total harmonic",
    ":FETCh:OBWidth:OBWidth:FERRor?": "The query returns the transmit frequency error in Hz.",
    ":FETCh:OBWidth:OBWidth?": "The query returns the occupied bandwidth in Hz.",
    ":FETCh:OBWidth?": "The query returns 2 values separated by commas: Occupied BandWidth (Hz) and Transmit Freq Error (Hz).",
    ":FETCh:TOIntercept:IP3?": "The query returns the smaller of the TOI intercepts of the 3rd Order Lower and the 3rd Order Upper.",
    ":FETCh:TOIntercept?": "The query returns the following values separated by commas : Frequency and amplitude of Base Lower (Hz), Frequency an...",
    ":FETCh:TPOWer?": "The query returns the Time-domain Power measurement result.",
    ":FORMat:BORDer": "Specify the transmission order of the binary data.",
    ":FORMat:BORDer?": "Specify the transmission order of the binary data.",
    ":FORMat:TRACe:DATA": "Specify the input/output format of the trace data.",
    ":FORMat:TRACe:DATA?": "Specify the input/output format of the trace data.",
    ":FORMat[:TRACe][:DATA]": "Specify the input/output format of the trace data.",
    ":FORMat[:TRACe][:DATA]?": "Specify the input/output format of the trace data.",
    ":FREQuency:CENTer": "Set the center frequency and the default unit is Hz.",
    ":FREQuency:CENTer:SET:STEP": "Set the center frequency to the current center frequency step.",
    ":FREQuency:CENTer:STEP": "Set the CF step and the default unit is Hz.",
    ":FREQuency:CENTer:STEP:AUTO": "Enable or disable the Auto setting mode of CF step.",
    ":FREQuency:CENTer:STEP:AUTO?": "Enable or disable the Auto setting mode of CF step.",
    ":FREQuency:CENTer:STEP?": "Set the CF step and the default unit is Hz.",
    ":FREQuency:CENTer?": "Set the center frequency and the default unit is Hz.",
    ":FREQuency:OFFSet": "Set the frequency offset and the default unit is Hz.",
    ":FREQuency:OFFSet?": "Set the frequency offset and the default unit is Hz.",
    ":FREQuency:SPAN": "Set the span and the default unit is Hz.",
    ":FREQuency:SPAN:FULL": "Set the span to the maximum.",
    ":FREQuency:SPAN:PREVious": "Recall the last span setting.",
    ":FREQuency:SPAN:ZIN": "Set the span to half of the current value.",
    ":FREQuency:SPAN:ZOUT": "Set the span to twice of the current value.",
    ":FREQuency:SPAN?": "Set the span and the default unit is Hz.",
    ":FREQuency:STARt": "Set the start frequency and the default unit is Hz.",
    ":FREQuency:STARt?": "Set the start frequency and the default unit is Hz.",
    ":FREQuency:STOP": "Set the stop frequency and the default unit is Hz.",
    ":FREQuency:STOP?": "Set the stop frequency and the default unit is Hz.",
    ":HCOPy:ABORt": "Cancel the current printing operation.",
    ":HCOPy:IMAGe:COLor": "Set the print color to Grey (OFF|0) or Color (ON|1).",
    ":HCOPy:IMAGe:COLor:STATe": "Set the print color to Grey (OFF|0) or Color (ON|1).",
    ":HCOPy:IMAGe:COLor:STATe?": "Set the print color to Grey (OFF|0) or Color (ON|1).",
    ":HCOPy:IMAGe:COLor?": "Set the print color to Grey (OFF|0) or Color (ON|1).",
    ":HCOPy:IMAGe:COLor[:STATe]": "Set the print color to Grey (OFF|0) or Color (ON|1).",
    ":HCOPy:IMAGe:COLor[:STATe]?": "Set the print color to Grey (OFF|0) or Color (ON|1).",
    ":HCOPy:IMAGe:FTYPe": "Set the image type to be printed to default or Exif/JPEG.",
    ":HCOPy:IMAGe:FTYPe?": "Set the image type to be printed to default or Exif/JPEG.",
    ":HCOPy:IMAGe:INVert": "Set whether to use inverted print.",
    ":HCOPy:IMAGe:INVert?": "Set whether to use inverted print.",
    ":HCOPy:IMAGe:PTIMe": "Set whether to print with date.",
    ":HCOPy:IMAGe:PTIMe?": "Set whether to print with date.",
    ":HCOPy:IMAGe:QUALity": "Set the print quality to default, normal, draft or fine.",
    ":HCOPy:IMAGe:QUALity?": "Set the print quality to default, normal, draft or fine.",
    ":HCOPy:IMMediate": "Perform the print operation.",
    ":HCOPy:PAGE:ORIentation": "Set the paper orientation to landscape or portrait.",
    ":HCOPy:PAGE:ORIentation?": "Set the paper orientation to landscape or portrait.",
    ":HCOPy:PAGE:PRINts": "Set the number of copies you want to print.",
    ":HCOPy:PAGE:PRINts?": "Set the number of copies you want to print.",
    ":HCOPy:PAGE:SIZE": "Set a page size to default, A4, A5, A6 or B5.",
    ":HCOPy:RESume": "Resume the suspended print operation.",
    ":HCOPy[:IMMediate]": "Perform the print operation.",
    ":HDISt:AVERage": "Turn on or off the average function of the Harmonic Distortion measurement.",
    ":HDISt:AVERage:COUNt": "Set the number of averages on the Harmonic Distortion measurement results.",
    ":HDISt:AVERage:COUNt?": "Set the number of averages on the Harmonic Distortion measurement results.",
    ":HDISt:AVERage:TCONtrol": "Set the average mode of the Harmonic Distortion measurement to exponential or repeat.",
    ":HDISt:AVERage:TCONtrol?": "Set the average mode of the Harmonic Distortion measurement to exponential or repeat.",
    ":HDISt:AVERage?": "Turn on or off the average function of the Harmonic Distortion measurement.",
    ":HDISt:NUMBers": "Set the number of harmonics for carrier measurement.",
    ":HDISt:NUMBers?": "Set the number of harmonics for carrier measurement.",
    ":HDISt:TIME": "Set the sweep time of the Harmonic measurement and the default unit is s.",
    ":HDISt:TIME:AUTO": "Turn on or off the Auto setting mode of sweep time for the harmonic measurement.",
    ":HDISt:TIME:AUTO?": "Turn on or off the Auto setting mode of sweep time for the harmonic measurement.",
    ":HDISt:TIME?": "Set the sweep time of the Harmonic measurement and the default unit is s.",
    ":INITiate:CONTinuous": "Select Continue (ON|1) or Single (OFF|0) sweep in non-measurement state.",
    ":INITiate:CONTinuous?": "Select Continue (ON|1) or Single (OFF|0) sweep in non-measurement state.",
    ":INITiate:IMMediate": "Initialize a sweep in non-measurement state.",
    ":INITiate:PAUSe": "Switch the instrument from “Wait For Trigger” to “Pause”.",
    ":INITiate:RESTart": "Restart the current measurement in “Idle” state.",
    ":INITiate:RESume": "Switch the instrument from “Pause” to “Wait For Trigger”.",
    ":INITiate[:IMMediate]": "Initialize a sweep in non-measurement state.",
    ":INPut:IMPedance": "Set the input impedance for voltage-to-power conversions.",
    ":INPut:IMPedance?": "Set the input impedance for voltage-to-power conversions.",
    ":MMEMory:DELete": "Delete the file with the specified filename.",
    ":MMEMory:DISK:FORMat": "Format the local disk.",
    ":MMEMory:DISK:INFormation?": "The query returns the current disk name, disk type, file system, used space and total capacity.",
    ":MMEMory:LOAD:CORRection": "Load the data from the specified file (.cbl) to make an amplitude correction.",
    ":MMEMory:LOAD:LIMit": "Load the edited limit line file (.lim) into the analyzer.",
    ":MMEMory:LOAD:MTABle": "Load the stored marker table file (.mkr or .csv) into the analyzer.",
    ":MMEMory:LOAD:SETUp": "Load the specified setup file (.set) into the instrument.",
    ":MMEMory:LOAD:STATe": "Load the specified status file (.sta) into the analyzer.",
    ":MMEMory:LOAD:TRACe": "Load the specified trace file (.trc) into the analyzer.",
    ":MMEMory:MOVE": "Rename the file specified by <file_name1> as <file_name2>.",
    ":MMEMory:STORe:CORRection": "Save the amplitude correction with a specified filename (.cbl or .csv).",
    ":MMEMory:STORe:LIMit": "Save the current edited limit line with the specified filename (.lim).",
    ":MMEMory:STORe:MTABle": "Save the marker table into a USB storage device with the specified filename (.mkr or .csv).",
    ":MMEMory:STORe:PTABle": "Save the peak table into a USB storage device with the specified filename (.csv).",
    ":MMEMory:STORe:RESults": "Save the current measurement results into a USB storage device with the specified filename (.csv).",
    ":MMEMory:STORe:SCReen": "Save the current screen into the local disk or a USB storage device with the specified filename (.bmp).",
    ":MMEMory:STORe:SETUp": "Save the current settings with the specified filename (.set).",
    ":MMEMory:STORe:STATe": "Save the current status into the internal memory of the anlyzer with the specified filename (.sta).",
    ":MMEMory:STORe:TRACe": "Save the trace with the specified filename (.trc or .csv).",
    ":OBWidth:AVERage": "Turn on or off the average function of the Occupied Bandwidth measurement.",
    ":OBWidth:AVERage:COUNt": "Set the number of averages of the Occupied Bandwidth measurement results.",
    ":OBWidth:AVERage:COUNt?": "Set the number of averages of the Occupied Bandwidth measurement results.",
    ":OBWidth:AVERage:TCONtrol": "Set the average mode of the Occupied Bandwidth measurement to exponential or repeat.",
    ":OBWidth:AVERage:TCONtrol?": "Set the average mode of the Occupied Bandwidth measurement to exponential or repeat.",
    ":OBWidth:FREQuency:SPAN": "Set the span of the Occupied Bandwidth measurement and the default unit is Hz.",
    ":OBWidth:FREQuency:SPAN?": "Set the span of the Occupied Bandwidth measurement and the default unit is Hz.",
    ":OBWidth:MAXHold:STATe": "Turn on or off the Max Hold function of the Occupied Bandwidth measurement.",
    ":OBWidth:MAXHold:STATe?": "Turn on or off the Max Hold function of the Occupied Bandwidth measurement.",
    ":OBWidth:PERCent": "Set the percentage of the signal power in the whole frequency span power.",
    ":OBWidth:PERCent?": "Set the percentage of the signal power in the whole frequency span power.",
    ":OUTPut:STATe": "Enable or disable the tracking generator output.",
    ":OUTPut:STATe?": "Enable or disable the tracking generator output.",
    ":OUTPut[:STATe]": "Enable or disable the tracking generator output.",
    ":OUTPut[:STATe]?": "Enable or disable the tracking generator output.",
    ":POWer:ARANge": "Adjust the parameters related to the amplitude within the current span range in order to make signal easier to observe.",
    ":POWer:ASCale": "Adjust the reference level and the scale automatically.",
    ":POWer:ATTenuation": "Set the attenuator of the front RF in dB.",
    ":POWer:ATTenuation:AUTO": "Enable or disable the Auto function of the attenuator.",
    ":POWer:ATTenuation:AUTO?": "Enable or disable the Auto function of the attenuator.",
    ":POWer:ATTenuation?": "Set the attenuator of the front RF in dB.",
    ":POWer:ATUNe": "Search signals within the full frequency range and adjust the frequency and amplitude for optimum display of signals.",
    ":POWer:GAIN": "Turn on or off the preamplifier.",
    ":POWer:GAIN?": "Turn on or off the preamplifier.",
    ":POWer:MIXer:RANGe": "Set the maximum power of the input mixer and the default unit is dBm.",
    ":POWer:MIXer:RANGe?": "Set the maximum power of the input mixer and the default unit is dBm.",
    ":READ:ACPower:LOWer?": "The command executes a measurement and returns the lower channel power.",
    ":READ:ACPower:MAIN?": "The command executes a measurement and returns the main channel power.",
    ":READ:ACPower:UPPer?": "The command executes a measurement and returns the upper channel power.",
    ":READ:ACPower?": "The command executes a measurement and returns 5 values separated by commas : Main channel power Upper channel power,...",
    ":READ:CHPower:CHPower?": "The command executes a measurement and returns the channel power.",
    ":READ:CHPower:DENSity?": "The command executes a measurement and returns the power spectral density.",
    ":READ:CHPower?": "The command executes a measurement and returns 2 values separated by commas: the channel power and the power spectral...",
    ":READ:CNRatio:CARRier?": "The command executes a measurement and returns the carrier power.",
    ":READ:CNRatio:CNRatio?": "The command executes a measurement and returns the noise ratio in dB.",
    ":READ:CNRatio:NOISe?": "The command executes a measurement and returns the noise power.",
    ":READ:CNRatio?": "The command executes a measurement and returns 3 values separated by commas: the carrier power, the noise power and c...",
    ":READ:EBWidth?": "The command executes a measurement and returns the measurement result of emission bandwidth in Hz.",
    ":READ:HARMonics:AMPLitude:ALL?": "The command executes a measurement and returns the amplitude values of the first ten harmonics separated by commas in...",
    ":READ:HARMonics:AMPLitude?": "The command executes a measurement and returns the specified harmonic amplitude.",
    ":READ:HARMonics:DISTortion?": "The command executes a measurement and returns the percentage of THD (total harmonic distortion).",
    ":READ:HARMonics:FREQuency:ALL?": "The command executes a measurement and returns the frequencies of the first ten harmonics separated by commas in Hz.",
    ":READ:HARMonics:FREQuency?": "The command executes a measurement and returns the specified harmonic frequency in Hz.",
    ":READ:HARMonics:FUNDamental?": "The command executes a measurement and returns the fundamental wave frequency in Hz.",
    ":READ:HARMonics?": "The command executes a measurement and returns the percentage of THD (total harmonic distortion).",
    ":READ:HARMonics[:DISTortion]?": "The command executes a measurement and returns the percentage of THD (total harmonic distortion).",
    ":READ:OBWidth:OBWidth:FERRor?": "The command executes a measurement and returns the transmit frequency error in Hz.",
    ":READ:OBWidth:OBWidth?": "The command executes a measurement and returns the carrier signal bandwidth in Hz.",
    ":READ:OBWidth?": "The command executes a measurement and returns 2 values separated by commas: the occupied bandwidth (Hz) and the rans...",
    ":READ:TOIntercept:IP3?": "The command executes a measurement and returns the smaller of the TOI intercepts of the 3rd Order Lower and the 3rd O...",
    ":READ:TOIntercept?": "The command executes a measurement and returns the following values separated by commas: Frequency and amplitude of B...",
    ":READ:TPOWer?": "The command executes a measurement and returns the Time-domain power measurement result.",
    ":ROSCillator:SOURce": "Select the internal or external reference source.",
    ":ROSCillator:SOURce?": "Select the internal or external reference source.",
    ":SENSe:ACPower:AVERage:COUNt": "Specify the number of averages on the adjacent channel power measurement results.",
    ":SENSe:ACPower:AVERage:COUNt?": "Specify the number of averages on the adjacent channel power measurement results.",
    ":SENSe:ACPower:AVERage:STATe": "Turn on or off the Average function of the adjacent channel power measurement.",
    ":SENSe:ACPower:AVERage:STATe?": "Turn on or off the Average function of the adjacent channel power measurement.",
    ":SENSe:ACPower:AVERage:TCONtrol": "Set the average mode of the adjacent channel power measurement to exponential or repeat.",
    ":SENSe:ACPower:AVERage:TCONtrol?": "Set the average mode of the adjacent channel power measurement to exponential or repeat.",
    ":SENSe:ACPower:BANDwidth:ACHannel": "Set the bandwidth of the adjacent channel and the default unit is Hz.",
    ":SENSe:ACPower:BANDwidth:ACHannel?": "Set the bandwidth of the adjacent channel and the default unit is Hz.",
    ":SENSe:ACPower:BANDwidth:INTegration": "Set the bandwidth of the main channel and the default unit is Hz.",
    ":SENSe:ACPower:BANDwidth:INTegration?": "Set the bandwidth of the main channel and the default unit is Hz.",
    ":SENSe:ACPower:CSPacing": "Set the center frequency difference between the main and adjacent channels and the default unit is Hz.",
    ":SENSe:ACPower:CSPacing?": "Set the center frequency difference between the main and adjacent channels and the default unit is Hz.",
    ":SENSe:BANDwidth:EMIFilter:STATe": "Enable or disable the EMI filter.",
    ":SENSe:BANDwidth:EMIFilter:STATe?": "Enable or disable the EMI filter.",
    ":SENSe:BANDwidth:RESolution": "Set the resolution bandwidth and the default unit is Hz.",
    ":SENSe:BANDwidth:RESolution:AUTO": "Enable or disable the Auto setting mode of resolution bandwidth.",
    ":SENSe:BANDwidth:RESolution:AUTO?": "Enable or disable the Auto setting mode of resolution bandwidth.",
    ":SENSe:BANDwidth:RESolution?": "Set the resolution bandwidth and the default unit is Hz.",
    ":SENSe:BANDwidth:VIDeo": "Set the video bandwidth and the default unit is Hz.",
    ":SENSe:BANDwidth:VIDeo:AUTO": "Enable or disable the Auto setting mode of video bandwidth.",
    ":SENSe:BANDwidth:VIDeo:AUTO?": "Enable or disable the Auto setting mode of video bandwidth.",
    ":SENSe:BANDwidth:VIDeo:RATio": "Set the ratio of VBW to RBW.",
    ":SENSe:BANDwidth:VIDeo:RATio?": "Set the ratio of VBW to RBW.",
    ":SENSe:BANDwidth:VIDeo?": "Set the video bandwidth and the default unit is Hz.",
    ":SENSe:CHPower:AVERage:COUNt": "Set the number of averages on the channel power measurement results.",
    ":SENSe:CHPower:AVERage:COUNt?": "Set the number of averages on the channel power measurement results.",
    ":SENSe:CHPower:AVERage:STATe": "Turn on or off the average function of the channel power measurement.",
    ":SENSe:CHPower:AVERage:STATe?": "Turn on or off the average function of the channel power measurement.",
    ":SENSe:CHPower:AVERage:TCONtrol": "Set the average mode of the channel power measurement to exponential or repeat.",
    ":SENSe:CHPower:AVERage:TCONtrol?": "Set the average mode of the channel power measurement to exponential or repeat.",
    ":SENSe:CHPower:BANDwidth:INTegration": "Set the integration bandwidth for the channel power measurement and the default unit is Hz.",
    ":SENSe:CHPower:BANDwidth:INTegration?": "Set the integration bandwidth for the channel power measurement and the default unit is Hz.",
    ":SENSe:CHPower:FREQuency:SPAN": "Set the channel span for the channel power measurement and the default unit is Hz.",
    ":SENSe:CHPower:FREQuency:SPAN?": "Set the channel span for the channel power measurement and the default unit is Hz.",
    ":SENSe:CNRatio:AVERage:COUNt": "Set the number of averages on the C/N Ratio measurement results.",
    ":SENSe:CNRatio:AVERage:COUNt?": "Set the number of averages on the C/N Ratio measurement results.",
    ":SENSe:CNRatio:AVERage:STATe": "Turn on or off the average function of the C/N Ratio measurement.",
    ":SENSe:CNRatio:AVERage:STATe?": "Turn on or off the average function of the C/N Ratio measurement.",
    ":SENSe:CNRatio:AVERage:TCONtrol": "Set the average mode of the C/N Ratio measurement to exponential or repeat.",
    ":SENSe:CNRatio:AVERage:TCONtrol?": "Set the average mode of the C/N Ratio measurement to exponential or repeat.",
    ":SENSe:CNRatio:BANDwidth:INTegration": "Set the carrier bandwidth and the default unit is Hz.",
    ":SENSe:CNRatio:BANDwidth:INTegration?": "Set the carrier bandwidth and the default unit is Hz.",
    ":SENSe:CNRatio:BANDwidth:NOISe": "Set the noise bandwidth and the default unit is Hz.",
    ":SENSe:CNRatio:BANDwidth:NOISe?": "Set the noise bandwidth and the default unit is Hz.",
    ":SENSe:CNRatio:OFFSet": "Set the center frequency difference between the carrier and noise and the default unit is Hz.",
    ":SENSe:CNRatio:OFFSet?": "Set the center frequency difference between the carrier and noise and the default unit is Hz.",
    ":SENSe:CORRection:CSET:ALL:DELete": "Delete all the amplitude correction data.",
    ":SENSe:CORRection:CSET:ALL:STATe": "Enable or disable the amplitude correction function.",
    ":SENSe:CORRection:CSET:ALL:STATe?": "Enable or disable the amplitude correction function.",
    ":SENSe:CORRection:CSET:TABLe:STATe": "Turn on or off the correction table.",
    ":SENSe:CORRection:CSET:TABLe:STATe?": "Turn on or off the correction table.",
    ":SENSe:CORRection:CSET<n>:DATA": "Create an amplitude correction curve on the basis of the current data.",
    ":SENSe:CORRection:CSET<n>:DATA:MERGe": "Add new correction data upon the current correction curve.",
    ":SENSe:CORRection:CSET<n>:DELete": "Delete the correction settings.",
    ":SENSe:CORRection:CSET<n>:STATe": "Turn on or off the specified amplitude correction.",
    ":SENSe:CORRection:CSET<n>:STATe?": "Turn on or off the specified amplitude correction.",
    ":SENSe:CORRection:CSET<n>:X:SPACing": "Set the amplitude correction mode to Lin or Log.",
    ":SENSe:CORRection:CSET<n>:X:SPACing?": "Set the amplitude correction mode to Lin or Log.",
    ":SENSe:DEMod": "Set the demodulation type.",
    ":SENSe:DEMod:STATe": "Turn on or off the demodulation.",
    ":SENSe:DEMod:STATe?": "Turn on or off the demodulation.",
    ":SENSe:DEMod:TIME": "Set the demodulating time and the default unit is s.",
    ":SENSe:DEMod:TIME?": "Set the demodulating time and the default unit is s.",
    ":SENSe:DEMod?": "Set the demodulation type.",
    ":SENSe:DETector:FUNCtion": "Set the detection type.",
    ":SENSe:EBWidth:AVERage:COUNt": "Set the number of averages of the Emission Bandwidth measurement results.",
    ":SENSe:EBWidth:AVERage:COUNt?": "Set the number of averages of the Emission Bandwidth measurement results.",
    ":SENSe:EBWidth:AVERage:STATe": "Turn on or off the average function of the Emission Bandwidth",
    ":SENSe:EBWidth:AVERage:STATe?": "Turn on or off the average function of the Emission Bandwidth",
    ":SENSe:EBWidth:AVERage:TCONtrol": "Set the average mode of the Emission Bandwidth measurement to exponential or repeat.",
    ":SENSe:EBWidth:AVERage:TCONtrol?": "Set the average mode of the Emission Bandwidth measurement to exponential or repeat.",
    ":SENSe:EBWidth:FREQuency:SPAN": "Set the span of the Emission Bandwidth measurement and the default unit is Hz.",
    ":SENSe:EBWidth:FREQuency:SPAN?": "Set the span of the Emission Bandwidth measurement and the default unit is Hz.",
    ":SENSe:EBWidth:MAXHold:STATe": "Turn on or off the Max Hold function.",
    ":SENSe:EBWidth:MAXHold:STATe?": "Turn on or off the Max Hold function.",
    ":SENSe:EBWidth:XDB": "Set the value of X dB of the emission bandwidth.",
    ":SENSe:EBWidth:XDB?": "Set the value of X dB of the emission bandwidth.",
    ":SENSe:FREQuency:CENTer": "Set the center frequency and the default unit is Hz.",
    ":SENSe:FREQuency:CENTer:SET:STEP": "Set the center frequency to the current center frequency step.",
    ":SENSe:FREQuency:CENTer:STEP:AUTO": "Enable or disable the Auto setting mode of CF step.",
    ":SENSe:FREQuency:CENTer:STEP:AUTO?": "Enable or disable the Auto setting mode of CF step.",
    ":SENSe:FREQuency:CENTer:STEP:INCRement": "Set the CF step and the default unit is Hz.",
    ":SENSe:FREQuency:CENTer:STEP:INCRement?": "Set the CF step and the default unit is Hz.",
    ":SENSe:FREQuency:CENTer?": "Set the center frequency and the default unit is Hz.",
    ":SENSe:FREQuency:OFFSet": "Set the frequency offset and the default unit is Hz.",
    ":SENSe:FREQuency:OFFSet?": "Set the frequency offset and the default unit is Hz.",
    ":SENSe:FREQuency:SPAN": "Set the span and the default unit is Hz.",
    ":SENSe:FREQuency:SPAN:FULL": "Set the span to the maximum.",
    ":SENSe:FREQuency:SPAN:PREVious": "Recall the last span setting.",
    ":SENSe:FREQuency:SPAN:ZIN": "Set the span to half of the current value.",
    ":SENSe:FREQuency:SPAN:ZOUT": "Set the span to twice of the current value.",
    ":SENSe:FREQuency:SPAN?": "Set the span and the default unit is Hz.",
    ":SENSe:FREQuency:STARt": "Set the start frequency and the default unit is Hz.",
    ":SENSe:FREQuency:STARt?": "Set the start frequency and the default unit is Hz.",
    ":SENSe:FREQuency:STOP": "Set the stop frequency and the default unit is Hz.",
    ":SENSe:FREQuency:STOP?": "Set the stop frequency and the default unit is Hz.",
    ":SENSe:HDISt:AVERage:COUNt": "Set the number of averages on the Harmonic Distortion measurement results.",
    ":SENSe:HDISt:AVERage:COUNt?": "Set the number of averages on the Harmonic Distortion measurement results.",
    ":SENSe:HDISt:AVERage:STATe": "Turn on or off the average function of the Harmonic Distortion measurement.",
    ":SENSe:HDISt:AVERage:STATe?": "Turn on or off the average function of the Harmonic Distortion measurement.",
    ":SENSe:HDISt:AVERage:TCONtrol": "Set the average mode of the Harmonic Distortion measurement to exponential or repeat.",
    ":SENSe:HDISt:AVERage:TCONtrol?": "Set the average mode of the Harmonic Distortion measurement to exponential or repeat.",
    ":SENSe:HDISt:NUMBers": "Set the number of harmonics for carrier measurement.",
    ":SENSe:HDISt:NUMBers?": "Set the number of harmonics for carrier measurement.",
    ":SENSe:HDISt:TIME": "Set the sweep time of the Harmonic measurement and the default unit is s.",
    ":SENSe:HDISt:TIME:AUTO:STATe": "Turn on or off the Auto setting mode of sweep time for the harmonic measurement.",
    ":SENSe:HDISt:TIME:AUTO:STATe?": "Turn on or off the Auto setting mode of sweep time for the harmonic measurement.",
    ":SENSe:HDISt:TIME?": "Set the sweep time of the Harmonic measurement and the default unit is s.",
    ":SENSe:OBWidth:AVERage": "Turn on or off the average function of the Occupied Bandwidth measurement.",
    ":SENSe:OBWidth:AVERage:COUNt": "Set the number of averages of the Occupied Bandwidth measurement results.",
    ":SENSe:OBWidth:AVERage:COUNt?": "Set the number of averages of the Occupied Bandwidth measurement results.",
    ":SENSe:OBWidth:AVERage:TCONtrol": "Set the average mode of the Occupied Bandwidth measurement to exponential or repeat.",
    ":SENSe:OBWidth:AVERage:TCONtrol?": "Set the average mode of the Occupied Bandwidth measurement to exponential or repeat.",
    ":SENSe:OBWidth:FREQuency:SPAN": "Set the span of the Occupied Bandwidth measurement and the default unit is Hz.",
    ":SENSe:OBWidth:FREQuency:SPAN?": "Set the span of the Occupied Bandwidth measurement and the default unit is Hz.",
    ":SENSe:OBWidth:MAXHold:STATe": "Turn on or off the Max Hold function of the Occupied Bandwidth measurement.",
    ":SENSe:OBWidth:MAXHold:STATe?": "Turn on or off the Max Hold function of the Occupied Bandwidth measurement.",
    ":SENSe:OBWidth:PERCent": "Set the percentage of the signal power in the whole frequency span power.",
    ":SENSe:OBWidth:PERCent?": "Set the percentage of the signal power in the whole frequency span power.",
    ":SENSe:POWer:ARANge": "Adjust the parameters related to the amplitude within the current span range in order to make signal easier to observe.",
    ":SENSe:POWer:ASCale": "Adjust the reference level and the scale automatically.",
    ":SENSe:POWer:ATUNe": "Search signals within the full frequency range and adjust the frequency and amplitude for optimum display of signals.",
    ":SENSe:POWer:RF:ATTenuation": "Set the attenuator of the front RF in dB.",
    ":SENSe:POWer:RF:ATTenuation:AUTO": "Enable or disable the Auto function of the attenuator.",
    ":SENSe:POWer:RF:ATTenuation:AUTO?": "Enable or disable the Auto function of the attenuator.",
    ":SENSe:POWer:RF:ATTenuation?": "Set the attenuator of the front RF in dB.",
    ":SENSe:POWer:RF:GAIN:STATe": "Turn on or off the preamplifier.",
    ":SENSe:POWer:RF:GAIN:STATe?": "Turn on or off the preamplifier.",
    ":SENSe:POWer:RF:MIXer:RANGe:UPPer": "Set the maximum power of the input mixer and the default unit is dBm.",
    ":SENSe:POWer:RF:MIXer:RANGe:UPPer?": "Set the maximum power of the input mixer and the default unit is dBm.",
    ":SENSe:ROSCillator:SOURce": "Select the internal or external reference source.",
    ":SENSe:ROSCillator:SOURce?": "Select the internal or external reference source.",
    ":SENSe:STATus:ANALyzer?": "Query the measurement settings of the analyzer.",
    ":SENSe:STATus:CORRections?": "Query the correction status.",
    ":SENSe:STATus:DEMod?": "Query the setting status of the demodulation.",
    ":SENSe:STATus:POWer?": "Query the setting status of the power measurement.",
    ":SENSe:STATus:TG?": "Query the setting status of TG (Tracking Generator).",
    ":SENSe:SWEep:COUNt": "Specify the number of sweeps in Single sweep mode.",
    ":SENSe:SWEep:COUNt:CURRent?": "The query returns the current number of sweeps in Single sweep mode, for example, 8.",
    ":SENSe:SWEep:COUNt?": "Specify the number of sweeps in Single sweep mode.",
    ":SENSe:SWEep:POINts": "Set the number of points obtained in each sweep.",
    ":SENSe:SWEep:POINts?": "Set the number of points obtained in each sweep.",
    ":SENSe:SWEep:TIME": "Set the sweep time of the analyzer within the specified span range and the default unit is s.",
    ":SENSe:SWEep:TIME:AUTO": "Turn on or off the Auto setting mode of the sweep time.",
    ":SENSe:SWEep:TIME:AUTO:RULes": "Set the auto mode of the sweep time to normal or accurate.",
    ":SENSe:SWEep:TIME:AUTO:RULes?": "Set the auto mode of the sweep time to normal or accurate.",
    ":SENSe:SWEep:TIME:AUTO?": "Turn on or off the Auto setting mode of the sweep time.",
    ":SENSe:SWEep:TIME?": "Set the sweep time of the analyzer within the specified span range and the default unit is s.",
    ":SENSe:TOI:AVERage:COUNt": "Set the number of averages on the TOI measurement results.",
    ":SENSe:TOI:AVERage:COUNt?": "Set the number of averages on the TOI measurement results.",
    ":SENSe:TOI:AVERage:STATe": "Turn on or off the average function of the TOI measurement.",
    ":SENSe:TOI:AVERage:STATe?": "Turn on or off the average function of the TOI measurement.",
    ":SENSe:TOI:AVERage:TCONtrol": "Set an average mode of the TOI measurement to exponential or repeat.",
    ":SENSe:TOI:AVERage:TCONtrol?": "Set an average mode of the TOI measurement to exponential or repeat.",
    ":SENSe:TOI:FREQuency:SPAN": "Set the span of the TOI measurement and the default unit is Hz.",
    ":SENSe:TOI:FREQuency:SPAN?": "Set the span of the TOI measurement and the default unit is Hz.",
    ":SENSe:TPOWer:AVERage:COUNt": "Set the number of averages on the T-Power measurement results.",
    ":SENSe:TPOWer:AVERage:COUNt?": "Set the number of averages on the T-Power measurement results.",
    ":SENSe:TPOWer:AVERage:STATe": "Turn on or off the average function of the Time-domain Power measurement.",
    ":SENSe:TPOWer:AVERage:STATe?": "Turn on or off the average function of the Time-domain Power measurement.",
    ":SENSe:TPOWer:AVERage:TCONtrol": "Set the average mode of the T-Power measurement to exponential or repeat.",
    ":SENSe:TPOWer:AVERage:TCONtrol?": "Set the average mode of the T-Power measurement to exponential or repeat.",
    ":SENSe:TPOWer:LLIMit": "Set the left limit of the Time-domain Power measurement and the default unit is s.",
    ":SENSe:TPOWer:LLIMit?": "Set the left limit of the Time-domain Power measurement and the default unit is s.",
    ":SENSe:TPOWer:MODE": "Set the type of the Time-domain Power measurement.",
    ":SENSe:TPOWer:MODE?": "Set the type of the Time-domain Power measurement.",
    ":SENSe:TPOWer:RLIMit": "Set the right limit of the Time-domain Power measurement and the default unit is s.",
    ":SENSe:TPOWer:RLIMit?": "Set the right limit of the Time-domain Power measurement and the default unit is s.",
    ":SOURce:CORRection:OFFSet": "Set the output amplitude offset for the tracking generator in dB.",
    ":SOURce:CORRection:OFFSet?": "Set the output amplitude offset for the tracking generator in dB.",
    ":SOURce:FREQuency:OFFSet": "Set the output frequency offset for the tracking generator and the default unit is Hz.",
    ":SOURce:FREQuency:OFFSet?": "Set the output frequency offset for the tracking generator and the default unit is Hz.",
    ":SOURce:POWer:LEVel:IMMediate:AMPLitude": "Set the output power of the tracking generator in the fixed power output mode and the default unit is dBm.",
    ":SOURce:POWer:LEVel:IMMediate:AMPLitude?": "Set the output power of the tracking generator in the fixed power output mode and the default unit is dBm.",
    ":SOURce:POWer:MODE": "Set the power output mode to fixed or sweep.",
    ":SOURce:POWer:MODE?": "Set the power output mode to fixed or sweep.",
    ":SOURce:POWer:SPAN": "Set the output amplitude range of the tracking generator in dB in fixed power output mode.",
    ":SOURce:POWer:SPAN?": "Set the output amplitude range of the tracking generator in dB in fixed power output mode.",
    ":SOURce:POWer:STARt": "Set the output power of the tracking generator in power sweep mode and the default unit is dBm.",
    ":SOURce:POWer:STARt?": "Set the output power of the tracking generator in power sweep mode and the default unit is dBm.",
    ":SOURce:POWer:SWEep": "Set the output power range of the tracking generator in dB in the power sweep mode.",
    ":SOURce:POWer:SWEep?": "Set the output power range of the tracking generator in dB in the power sweep mode.",
    ":SOURce:TRACe:REF:STATe": "Set whether to display the reference trace.",
    ":SOURce:TRACe:REF:STATe?": "Set whether to display the reference trace.",
    ":SOURce:TRACe:STORref": "Save the normalized trace.",
    ":STATus:ANALyzer?": "Query the measurement settings of the analyzer.",
    ":STATus:CORRections?": "Query the correction status.",
    ":STATus:DEMod?": "Query the setting status of the demodulation.",
    ":STATus:OPERation:CONDition?": "The query returns the value of the condition register for the operation status register.",
    ":STATus:OPERation:ENABle": "Set the value of the enable register for the operation status register.",
    ":STATus:OPERation:ENABle?": "Set the value of the enable register for the operation status register.",
    ":STATus:OPERation:EVENt?": "The query returns the value of the event register in the operation status register.",
    ":STATus:OPERation?": "The query returns the value of the event register in the operation status register.",
    ":STATus:OPERation[:EVENt]?": "The query returns the value of the event register in the operation status register.",
    ":STATus:POWer?": "Query the setting status of the power measurement.",
    ":STATus:PRESet": "Clear the enable registers in both the operation status register and questionable status register.",
    ":STATus:QUEStionable:CONDition?": "The query returns the value of the condition register in the questionable status register.",
    ":STATus:QUEStionable:ENABle": "Set the value of the enable register in the questionable status register.",
    ":STATus:QUEStionable:ENABle?": "Set the value of the enable register in the questionable status register.",
    ":STATus:QUEStionable:EVENt?": "The query returns the value of the event register in the questionable status register.",
    ":STATus:QUEStionable?": "The query returns the value of the event register in the questionable status register.",
    ":STATus:QUEStionable[:EVENt]?": "The query returns the value of the event register in the questionable status register.",
    ":STATus:TG?": "Query the setting status of TG (Tracking Generator).",
    ":SWEep:COUNt": "Specify the number of sweeps in Single sweep mode.",
    ":SWEep:COUNt:CURRent?": "The query returns the current number of sweeps in Single sweep mode, for example, 8.",
    ":SWEep:COUNt?": "Specify the number of sweeps in Single sweep mode.",
    ":SWEep:POINts": "Set the number of points obtained in each sweep.",
    ":SWEep:POINts?": "Set the number of points obtained in each sweep.",
    ":SWEep:TIME": "Set the sweep time of the analyzer within the specified span range and the default unit is s.",
    ":SWEep:TIME:AUTO": "Turn on or off the Auto setting mode of the sweep time.",
    ":SWEep:TIME:AUTO?": "Turn on or off the Auto setting mode of the sweep time.",
    ":SWEep:TIME?": "Set the sweep time of the analyzer within the specified span range and the default unit is s.",
    ":SYSTem:COMMunicate:APORt": "Select a communication port.",
    ":SYSTem:COMMunicate:APORt?": "Select a communication port.",
    ":SYSTem:COMMunicate:GPIB:ADDRess": "Set the GPIB address.",
    ":SYSTem:COMMunicate:GPIB:ADDRess?": "Set the GPIB address.",
    ":SYSTem:COMMunicate:GPIB:SELF:ADDRess": "Set the GPIB address.",
    ":SYSTem:COMMunicate:GPIB:SELF:ADDRess?": "Set the GPIB address.",
    ":SYSTem:COMMunicate:GPIB[:SELF]:ADDRess": "Set the GPIB address.",
    ":SYSTem:COMMunicate:GPIB[:SELF]:ADDRess?": "Set the GPIB address.",
    ":SYSTem:COMMunicate:LAN:AUToip:STATe": "Turn on or off the Auto IP.",
    ":SYSTem:COMMunicate:LAN:AUToip:STATe?": "Turn on or off the Auto IP.",
    ":SYSTem:COMMunicate:LAN:DHCP:STATe": "Turn on or off the DHCP.",
    ":SYSTem:COMMunicate:LAN:DHCP:STATe?": "Turn on or off the DHCP.",
    ":SYSTem:COMMunicate:LAN:IP:ADDress": "Set the IP address.",
    ":SYSTem:COMMunicate:LAN:IP:ADDress?": "Set the IP address.",
    ":SYSTem:COMMunicate:LAN:IP:DNSServer": "Set the DNS server address.",
    ":SYSTem:COMMunicate:LAN:IP:DNSServer?": "Set the DNS server address.",
    ":SYSTem:COMMunicate:LAN:IP:GATeway": "Specify a default gateway.",
    ":SYSTem:COMMunicate:LAN:IP:GATeway?": "Specify a default gateway.",
    ":SYSTem:COMMunicate:LAN:IP:SUBMask": "Set the submask.",
    ":SYSTem:COMMunicate:LAN:IP:SUBMask?": "Set the submask.",
    ":SYSTem:COMMunicate:LAN:MANuip:STATe": "Turn on or off the Manual IP.",
    ":SYSTem:COMMunicate:LAN:MANuip:STATe?": "Turn on or off the Manual IP.",
    ":SYSTem:COMMunicate:LAN:RESet": "Reset the LAN setting.",
    ":SYSTem:COMMunicate:LAN:SELF:AUToip:STATe": "Turn on or off the Auto IP.",
    ":SYSTem:COMMunicate:LAN:SELF:AUToip:STATe?": "Turn on or off the Auto IP.",
    ":SYSTem:COMMunicate:LAN:SELF:DHCP:STATe": "Turn on or off the DHCP.",
    ":SYSTem:COMMunicate:LAN:SELF:DHCP:STATe?": "Turn on or off the DHCP.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:ADDress": "Set the IP address.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:ADDress?": "Set the IP address.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:DNSServer": "Set the DNS server address.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:DNSServer?": "Set the DNS server address.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:GATeway": "Specify a default gateway.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:GATeway?": "Specify a default gateway.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:SUBMask": "Set the submask.",
    ":SYSTem:COMMunicate:LAN:SELF:IP:SUBMask?": "Set the submask.",
    ":SYSTem:COMMunicate:LAN:SELF:MANuip:STATe": "Turn on or off the Manual IP.",
    ":SYSTem:COMMunicate:LAN:SELF:MANuip:STATe?": "Turn on or off the Manual IP.",
    ":SYSTem:COMMunicate:LAN:SELF:RESet": "Reset the LAN setting.",
    ":SYSTem:COMMunicate:LAN[:SELF]:AUToip:STATe": "Turn on or off the Auto IP.",
    ":SYSTem:COMMunicate:LAN[:SELF]:AUToip:STATe?": "Turn on or off the Auto IP.",
    ":SYSTem:COMMunicate:LAN[:SELF]:DHCP:STATe": "Turn on or off the DHCP.",
    ":SYSTem:COMMunicate:LAN[:SELF]:DHCP:STATe?": "Turn on or off the DHCP.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:ADDress": "Set the IP address.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:ADDress?": "Set the IP address.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:DNSServer": "Set the DNS server address.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:DNSServer?": "Set the DNS server address.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:GATeway": "Specify a default gateway.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:GATeway?": "Specify a default gateway.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:SUBMask": "Set the submask.",
    ":SYSTem:COMMunicate:LAN[:SELF]:IP:SUBMask?": "Set the submask.",
    ":SYSTem:COMMunicate:LAN[:SELF]:MANuip:STATe": "Turn on or off the Manual IP.",
    ":SYSTem:COMMunicate:LAN[:SELF]:MANuip:STATe?": "Turn on or off the Manual IP.",
    ":SYSTem:COMMunicate:LAN[:SELF]:RESet": "Reset the LAN setting.",
    ":SYSTem:COMMunicate:USB:ADDRess?": "View the USB device address.",
    ":SYSTem:COMMunicate:USB:CLASs": "Set the USB device type.",
    ":SYSTem:COMMunicate:USB:CLASs?": "Set the USB device type.",
    ":SYSTem:COMMunicate:USB:SELF:ADDRess?": "View the USB device address.",
    ":SYSTem:COMMunicate:USB:SELF:CLASs": "Set the USB device type.",
    ":SYSTem:COMMunicate:USB:SELF:CLASs?": "Set the USB device type.",
    ":SYSTem:COMMunicate:USB[:SELF]:ADDRess?": "View the USB device address.",
    ":SYSTem:COMMunicate:USB[:SELF]:CLASs": "Set the USB device type.",
    ":SYSTem:COMMunicate:USB[:SELF]:CLASs?": "Set the USB device type.",
    ":SYSTem:CONFigure:INFormation?": "The query returns the same system information as those displayed on the screen of the front panel.",
    ":SYSTem:CONFigure:MESSage?": "The query returns the system messages that have been displayed recently.",
    ":SYSTem:DATE": "Set the real-time date of the analyzer.",
    ":SYSTem:DATE?": "Set the real-time date of the analyzer.",
    ":SYSTem:ERRor:NEXT?": "The query returns the error item that first entered the error queue and deletes it.",
    ":SYSTem:ERRor?": "The query returns the error item that first entered the error queue and deletes it.",
    ":SYSTem:ERRor[:NEXT]?": "The query returns the error item that first entered the error queue and deletes it.",
    ":SYSTem:FSWItch": "Set whether the front switch is valid.",
    ":SYSTem:FSWItch:STATe": "Set whether the front switch is valid.",
    ":SYSTem:FSWItch:STATe?": "Set whether the front switch is valid.",
    ":SYSTem:FSWItch?": "Set whether the front switch is valid.",
    ":SYSTem:FSWItch[:STATe]": "Set whether the front switch is valid.",
    ":SYSTem:FSWItch[:STATe]?": "Set whether the front switch is valid.",
    ":SYSTem:LANGuage": "Set the display language.",
    ":SYSTem:LANGuage?": "Set the display language.",
    ":SYSTem:LKEY": "Install and enable the options of the analyzer.",
    ":SYSTem:LKEY?": "Install and enable the options of the analyzer.",
    ":SYSTem:OPTions?": "The query returns the installed option list, including the option number, the license key and the state of activation.",
    ":SYSTem:PON:TYPE": "Set the system to recall the last setting or the preset setting at poer-on.",
    ":SYSTem:PON:TYPE?": "Set the system to recall the last setting or the preset setting at poer-on.",
    ":SYSTem:PRESet": "Recall the system preset settings.",
    ":SYSTem:PRESet:SAVE": "Save the user settings.",
    ":SYSTem:PRESet:TYPE": "Specify the system preset type to factory or user.",
    ":SYSTem:PRESet:TYPE?": "Specify the system preset type to factory or user.",
    ":SYSTem:PRESet:USER:SAVE": "Save the user settings.",
    ":SYSTem:PRESet[:USER]:SAVE": "Save the user settings.",
    ":SYSTem:PROBe": "Set the probe status.",
    ":SYSTem:PROBe:STATe": "Set the probe status.",
    ":SYSTem:PROBe:STATe?": "Set the probe status.",
    ":SYSTem:PROBe?": "Set the probe status.",
    ":SYSTem:PROBe[:STATe]": "Set the probe status.",
    ":SYSTem:PROBe[:STATe]?": "Set the probe status.",
    ":SYSTem:SPEaker": "Turn on or off the internal speaker.",
    ":SYSTem:SPEaker:STATe": "Turn on or off the internal speaker.",
    ":SYSTem:SPEaker:STATe?": "Turn on or off the internal speaker.",
    ":SYSTem:SPEaker:VOLume": "Adjust the volume of the speaker.",
    ":SYSTem:SPEaker:VOLume?": "Adjust the volume of the speaker.",
    ":SYSTem:SPEaker?": "Turn on or off the internal speaker.",
    ":SYSTem:SPEaker[:STATe]": "Turn on or off the internal speaker.",
    ":SYSTem:SPEaker[:STATe]?": "Turn on or off the internal speaker.",
    ":SYSTem:TIME": "Set the time of the analyzer clock.",
    ":SYSTem:TIME?": "Set the time of the analyzer clock.",
    ":SYSTem:VERSion?": "The query returns the SCPI version number of the analyzer (1999.0).",
    ":TOI:AVERage": "Turn on or off the average function of the TOI measurement.",
    ":TOI:AVERage:COUNt": "Set the number of averages on the TOI measurement results.",
    ":TOI:AVERage:COUNt?": "Set the number of averages on the TOI measurement results.",
    ":TOI:AVERage:TCONtrol": "Set an average mode of the TOI measurement to exponential or repeat.",
    ":TOI:AVERage:TCONtrol?": "Set an average mode of the TOI measurement to exponential or repeat.",
    ":TOI:AVERage?": "Turn on or off the average function of the TOI measurement.",
    ":TOI:FREQuency:SPAN": "Set the span of the TOI measurement and the default unit is Hz.",
    ":TOI:FREQuency:SPAN?": "Set the span of the TOI measurement and the default unit is Hz.",
    ":TPOWer:AVERage": "Turn on or off the average function of the Time-domain Power measurement.",
    ":TPOWer:AVERage:COUNt": "Set the number of averages on the T-Power measurement results.",
    ":TPOWer:AVERage:COUNt?": "Set the number of averages on the T-Power measurement results.",
    ":TPOWer:AVERage:TCONtrol": "Set the average mode of the T-Power measurement to exponential or repeat.",
    ":TPOWer:AVERage:TCONtrol?": "Set the average mode of the T-Power measurement to exponential or repeat.",
    ":TPOWer:AVERage?": "Turn on or off the average function of the Time-domain Power measurement.",
    ":TPOWer:LLIMit": "Set the left limit of the Time-domain Power measurement and the default unit is s.",
    ":TPOWer:LLIMit?": "Set the left limit of the Time-domain Power measurement and the default unit is s.",
    ":TPOWer:MODE": "Set the type of the Time-domain Power measurement.",
    ":TPOWer:MODE?": "Set the type of the Time-domain Power measurement.",
    ":TPOWer:RLIMit": "Set the right limit of the Time-domain Power measurement and the default unit is s.",
    ":TPOWer:RLIMit?": "Set the right limit of the Time-domain Power measurement and the default unit is s.",
    ":TRACe:AVERage:CLEar": "Clear the number of averages.",
    ":TRACe:AVERage:COUNt": "Set the number of averages of the trace.",
    ":TRACe:AVERage:COUNt:CURRent?": "The query returns the current number of averages of the trace, for example, 1.",
    ":TRACe:AVERage:COUNt?": "Set the number of averages of the trace.",
    ":TRACe:AVERage:RESet": "Execute the trace average reset operation.",
    ":TRACe:CLEar:ALL": "Clear all the traces, that is, set the type of all the traces to BLANK (Off).",
    ":TRACe:DATA": "Load the user data into the specified trace.",
    ":TRACe:MATH:A": "Select a trace as the trace A for the trace math from T1, T2 or T3.",
    ":TRACe:MATH:A?": "Select a trace as the trace A for the trace math from T1, T2 or T3.",
    ":TRACe:MATH:B": "Select a trace as the trace B for the trace math from T1, T2 or T3.",
    ":TRACe:MATH:B?": "Select a trace as the trace B for the trace math from T1, T2 or T3.",
    ":TRACe:MATH:CONSt": "Set the constant of the trace math in dB.",
    ":TRACe:MATH:CONSt?": "Set the constant of the trace math in dB.",
    ":TRACe:MATH:PEAK:DATA?": "Query the frequency (Hz) and amplitude (has the same unit as Y axis) from Peak Table.",
    ":TRACe:MATH:PEAK:POINts?": "Query the number of peak readout in the Peak Table and return an integer within 0 and 10.",
    ":TRACe:MATH:PEAK:SORT": "Set the sorting mode of the Peak Table.",
    ":TRACe:MATH:PEAK:SORT?": "Set the sorting mode of the Peak Table.",
    ":TRACe:MATH:PEAK:TABLe:STATe": "Turn on or off the Peak Table.",
    ":TRACe:MATH:PEAK:TABLe:STATe?": "Turn on or off the Peak Table.",
    ":TRACe:MATH:PEAK:THReshold": "Set the readout type of the peak in the Peak Table.",
    ":TRACe:MATH:PEAK:THReshold?": "Set the readout type of the peak in the Peak Table.",
    ":TRACe:MATH:PEAK?": "Query the frequency (Hz) and amplitude (has the same unit as Y axis) from Peak Table.",
    ":TRACe:MATH:PEAK[:DATA]?": "Query the frequency (Hz) and amplitude (has the same unit as Y axis) from Peak Table.",
    ":TRACe:MATH:STATe": "Turn on or off the math trace operation.",
    ":TRACe:MATH:STATe?": "Turn on or off the math trace operation.",
    ":TRACe:MATH:TYPE": "Set the operation type of the trace.",
    ":TRACe:MATH:TYPE?": "Set the operation type of the trace.",
    ":TRACe<n>:AVERage:TYPE": "Set the average type of the trace.",
    ":TRACe<n>:AVERage:TYPE?": "Set the average type of the trace.",
    ":TRACe<n>:MODE": "Set the type of the specified trace.",
    ":TRACe[:DATA]": "Load the user data into the specified trace.",
    ":TRIGger:SEQuence:EXTernal:SLOPe": "Set the external trigger edge.",
    ":TRIGger:SEQuence:EXTernal:SLOPe?": "Set the external trigger edge.",
    ":TRIGger:SEQuence:SOURce": "Se the trigger type.",
    ":TRIGger:SEQuence:SOURce?": "Se the trigger type.",
    ":TRIGger:SEQuence:VIDeo:LEVel": "Set the Video trigger level and the default unit is dBm.",
    ":TRIGger:SEQuence:VIDeo:LEVel?": "Set the Video trigger level and the default unit is dBm.",
    ":UNIT:POWer": "Set the the input, output and displayed amplitude unit.",
    ":UNIT:POWer?": "Set the the input, output and displayed amplitude unit.",
    "CALibration": "Calibrate immediately.",
    "DEMod": "Set the demodulation type.",
    "DEMod?": "Set the demodulation type.",
    "DETector": "Set the detection type.",
    "FORMat": "Specify the input/output format of the trace data.",
    "FORMat?": "Specify the input/output format of the trace data.",
    "HCOPy": "Perform the print operation.",
    "INITiate": "Initialize a sweep in non-measurement state.",
    "OUTPut": "Enable or disable the tracking generator output.",
    "OUTPut?": "Enable or disable the tracking generator output.",
    "TRACe": "Load the user data into the specified trace.",
    "[:SENSe]:ACPower:AVERage:COUNt": "Specify the number of averages on the adjacent channel power measurement results.",
    "[:SENSe]:ACPower:AVERage:COUNt?": "Specify the number of averages on the adjacent channel power measurement results.",
    "[:SENSe]:ACPower:AVERage:TCONtrol": "Set the average mode of the adjacent channel power measurement to exponential or repeat.",
    "[:SENSe]:ACPower:AVERage:TCONtrol?": "Set the average mode of the adjacent channel power measurement to exponential or repeat.",
    "[:SENSe]:ACPower:AVERage[:STATe]": "Turn on or off the Average function of the adjacent channel power measurement.",
    "[:SENSe]:ACPower:AVERage[:STATe]?": "Turn on or off the Average function of the adjacent channel power measurement.",
    "[:SENSe]:ACPower:BANDwidth:ACHannel": "Set the bandwidth of the adjacent channel and the default unit is Hz.",
    "[:SENSe]:ACPower:BANDwidth:ACHannel?": "Set the bandwidth of the adjacent channel and the default unit is Hz.",
    "[:SENSe]:ACPower:BANDwidth:INTegration": "Set the bandwidth of the main channel and the default unit is Hz.",
    "[:SENSe]:ACPower:BANDwidth:INTegration?": "Set the bandwidth of the main channel and the default unit is Hz.",
    "[:SENSe]:ACPower:CSPacing": "Set the center frequency difference between the main and adjacent channels and the default unit is Hz.",
    "[:SENSe]:ACPower:CSPacing?": "Set the center frequency difference between the main and adjacent channels and the default unit is Hz.",
    "[:SENSe]:BANDwidth:EMIFilter:STATe": "Enable or disable the EMI filter.",
    "[:SENSe]:BANDwidth:EMIFilter:STATe?": "Enable or disable the EMI filter.",
    "[:SENSe]:BANDwidth:RESolution": "Set the resolution bandwidth and the default unit is Hz.",
    "[:SENSe]:BANDwidth:RESolution:AUTO": "Enable or disable the Auto setting mode of resolution bandwidth.",
    "[:SENSe]:BANDwidth:RESolution:AUTO?": "Enable or disable the Auto setting mode of resolution bandwidth.",
    "[:SENSe]:BANDwidth:RESolution?": "Set the resolution bandwidth and the default unit is Hz.",
    "[:SENSe]:BANDwidth:VIDeo": "Set the video bandwidth and the default unit is Hz.",
    "[:SENSe]:BANDwidth:VIDeo:AUTO": "Enable or disable the Auto setting mode of video bandwidth.",
    "[:SENSe]:BANDwidth:VIDeo:AUTO?": "Enable or disable the Auto setting mode of video bandwidth.",
    "[:SENSe]:BANDwidth:VIDeo:RATio": "Set the ratio of VBW to RBW.",
    "[:SENSe]:BANDwidth:VIDeo:RATio?": "Set the ratio of VBW to RBW.",
    "[:SENSe]:BANDwidth:VIDeo?": "Set the video bandwidth and the default unit is Hz.",
    "[:SENSe]:CHPower:AVERage:COUNt": "Set the number of averages on the channel power measurement results.",
    "[:SENSe]:CHPower:AVERage:COUNt?": "Set the number of averages on the channel power measurement results.",
    "[:SENSe]:CHPower:AVERage:TCONtrol": "Set the average mode of the channel power measurement to exponential or repeat.",
    "[:SENSe]:CHPower:AVERage:TCONtrol?": "Set the average mode of the channel power measurement to exponential or repeat.",
    "[:SENSe]:CHPower:AVERage[:STATe]": "Turn on or off the average function of the channel power measurement.",
    "[:SENSe]:CHPower:AVERage[:STATe]?": "Turn on or off the average function of the channel power measurement.",
    "[:SENSe]:CHPower:BANDwidth:INTegration": "Set the integration bandwidth for the channel power measurement and the default unit is Hz.",
    "[:SENSe]:CHPower:BANDwidth:INTegration?": "Set the integration bandwidth for the channel power measurement and the default unit is Hz.",
    "[:SENSe]:CHPower:FREQuency:SPAN": "Set the channel span for the channel power measurement and the default unit is Hz.",
    "[:SENSe]:CHPower:FREQuency:SPAN?": "Set the channel span for the channel power measurement and the default unit is Hz.",
    "[:SENSe]:CNRatio:AVERage:COUNt": "Set the number of averages on the C/N Ratio measurement results.",
    "[:SENSe]:CNRatio:AVERage:COUNt?": "Set the number of averages on the C/N Ratio measurement results.",
    "[:SENSe]:CNRatio:AVERage:TCONtrol": "Set the average mode of the C/N Ratio measurement to exponential or repeat.",
    "[:SENSe]:CNRatio:AVERage:TCONtrol?": "Set the average mode of the C/N Ratio measurement to exponential or repeat.",
    "[:SENSe]:CNRatio:AVERage[:STATe]": "Turn on or off the average function of the C/N Ratio measurement.",
    "[:SENSe]:CNRatio:AVERage[:STATe]?": "Turn on or off the average function of the C/N Ratio measurement.",
    "[:SENSe]:CNRatio:BANDwidth:INTegration": "Set the carrier bandwidth and the default unit is Hz.",
    "[:SENSe]:CNRatio:BANDwidth:INTegration?": "Set the carrier bandwidth and the default unit is Hz.",
    "[:SENSe]:CNRatio:BANDwidth:NOISe": "Set the noise bandwidth and the default unit is Hz.",
    "[:SENSe]:CNRatio:BANDwidth:NOISe?": "Set the noise bandwidth and the default unit is Hz.",
    "[:SENSe]:CNRatio:OFFSet": "Set the center frequency difference between the carrier and noise and the default unit is Hz.",
    "[:SENSe]:CNRatio:OFFSet?": "Set the center frequency difference between the carrier and noise and the default unit is Hz.",
    "[:SENSe]:CORRection:CSET:ALL:DELete": "Delete all the amplitude correction data.",
    "[:SENSe]:CORRection:CSET:ALL[:STATe]": "Enable or disable the amplitude correction function.",
    "[:SENSe]:CORRection:CSET:ALL[:STATe]?": "Enable or disable the amplitude correction function.",
    "[:SENSe]:CORRection:CSET:TABLe:STATe": "Turn on or off the correction table.",
    "[:SENSe]:CORRection:CSET:TABLe:STATe?": "Turn on or off the correction table.",
    "[:SENSe]:CORRection:CSET<n>:DATA": "Create an amplitude correction curve on the basis of the current data.",
    "[:SENSe]:CORRection:CSET<n>:DATA:MERGe": "Add new correction data upon the current correction curve.",
    "[:SENSe]:CORRection:CSET<n>:DELete": "Delete the correction settings.",
    "[:SENSe]:CORRection:CSET<n>:X:SPACing": "Set the amplitude correction mode to Lin or Log.",
    "[:SENSe]:CORRection:CSET<n>:X:SPACing?": "Set the amplitude correction mode to Lin or Log.",
    "[:SENSe]:CORRection:CSET<n>[:STATe]": "Turn on or off the specified amplitude correction.",
    "[:SENSe]:CORRection:CSET<n>[:STATe]?": "Turn on or off the specified amplitude correction.",
    "[:SENSe]:DEMod": "Set the demodulation type.",
    "[:SENSe]:DEMod:STATe": "Turn on or off the demodulation.",
    "[:SENSe]:DEMod:STATe?": "Turn on or off the demodulation.",
    "[:SENSe]:DEMod:TIME": "Set the demodulating time and the default unit is s.",
    "[:SENSe]:DEMod:TIME?": "Set the demodulating time and the default unit is s.",
    "[:SENSe]:DEMod?": "Set the demodulation type.",
    "[:SENSe]:DETector[:FUNCtion]": "Set the detection type.",
    "[:SENSe]:EBWidth:AVERage:COUNt": "Set the number of averages of the Emission Bandwidth measurement results.",
    "[:SENSe]:EBWidth:AVERage:COUNt?": "Set the number of averages of the Emission Bandwidth measurement results.",
    "[:SENSe]:EBWidth:AVERage:TCONtrol": "Set the average mode of the Emission Bandwidth measurement to exponential or repeat.",
    "[:SENSe]:EBWidth:AVERage:TCONtrol?": "Set the average mode of the Emission Bandwidth measurement to exponential or repeat.",
    "[:SENSe]:EBWidth:AVERage[:STATe]": "Turn on or off the average function of the Emission Bandwidth",
    "[:SENSe]:EBWidth:AVERage[:STATe]?": "Turn on or off the average function of the Emission Bandwidth",
    "[:SENSe]:EBWidth:FREQuency:SPAN": "Set the span of the Emission Bandwidth measurement and the default unit is Hz.",
    "[:SENSe]:EBWidth:FREQuency:SPAN?": "Set the span of the Emission Bandwidth measurement and the default unit is Hz.",
    "[:SENSe]:EBWidth:MAXHold:STATe": "Turn on or off the Max Hold function.",
    "[:SENSe]:EBWidth:MAXHold:STATe?": "Turn on or off the Max Hold function.",
    "[:SENSe]:EBWidth:XDB": "Set the value of X dB of the emission bandwidth.",
    "[:SENSe]:EBWidth:XDB?": "Set the value of X dB of the emission bandwidth.",
    "[:SENSe]:FREQuency:CENTer": "Set the center frequency and the default unit is Hz.",
    "[:SENSe]:FREQuency:CENTer:SET:STEP": "Set the center frequency to the current center frequency step.",
    "[:SENSe]:FREQuency:CENTer:STEP:AUTO": "Enable or disable the Auto setting mode of CF step.",
    "[:SENSe]:FREQuency:CENTer:STEP:AUTO?": "Enable or disable the Auto setting mode of CF step.",
    "[:SENSe]:FREQuency:CENTer:STEP[:INCRement]": "Set the CF step and the default unit is Hz.",
    "[:SENSe]:FREQuency:CENTer:STEP[:INCRement]?": "Set the CF step and the default unit is Hz.",
    "[:SENSe]:FREQuency:CENTer?": "Set the center frequency and the default unit is Hz.",
    "[:SENSe]:FREQuency:OFFSet": "Set the frequency offset and the default unit is Hz.",
    "[:SENSe]:FREQuency:OFFSet?": "Set the frequency offset and the default unit is Hz.",
    "[:SENSe]:FREQuency:SPAN": "Set the span and the default unit is Hz.",
    "[:SENSe]:FREQuency:SPAN:FULL": "Set the span to the maximum.",
    "[:SENSe]:FREQuency:SPAN:PREVious": "Recall the last span setting.",
    "[:SENSe]:FREQuency:SPAN:ZIN": "Set the span to half of the current value.",
    "[:SENSe]:FREQuency:SPAN:ZOUT": "Set the span to twice of the current value.",
    "[:SENSe]:FREQuency:SPAN?": "Set the span and the default unit is Hz.",
    "[:SENSe]:FREQuency:STARt": "Set the start frequency and the default unit is Hz.",
    "[:SENSe]:FREQuency:STARt?": "Set the start frequency and the default unit is Hz.",
    "[:SENSe]:FREQuency:STOP": "Set the stop frequency and the default unit is Hz.",
    "[:SENSe]:FREQuency:STOP?": "Set the stop frequency and the default unit is Hz.",
    "[:SENSe]:HDISt:AVERage:COUNt": "Set the number of averages on the Harmonic Distortion measurement results.",
    "[:SENSe]:HDISt:AVERage:COUNt?": "Set the number of averages on the Harmonic Distortion measurement results.",
    "[:SENSe]:HDISt:AVERage:TCONtrol": "Set the average mode of the Harmonic Distortion measurement to exponential or repeat.",
    "[:SENSe]:HDISt:AVERage:TCONtrol?": "Set the average mode of the Harmonic Distortion measurement to exponential or repeat.",
    "[:SENSe]:HDISt:AVERage[:STATe]": "Turn on or off the average function of the Harmonic Distortion measurement.",
    "[:SENSe]:HDISt:AVERage[:STATe]?": "Turn on or off the average function of the Harmonic Distortion measurement.",
    "[:SENSe]:HDISt:NUMBers": "Set the number of harmonics for carrier measurement.",
    "[:SENSe]:HDISt:NUMBers?": "Set the number of harmonics for carrier measurement.",
    "[:SENSe]:HDISt:TIME": "Set the sweep time of the Harmonic measurement and the default unit is s.",
    "[:SENSe]:HDISt:TIME:AUTO[:STATe]": "Turn on or off the Auto setting mode of sweep time for the harmonic measurement.",
    "[:SENSe]:HDISt:TIME:AUTO[:STATe]?": "Turn on or off the Auto setting mode of sweep time for the harmonic measurement.",
    "[:SENSe]:HDISt:TIME?": "Set the sweep time of the Harmonic measurement and the default unit is s.",
    "[:SENSe]:OBWidth:AVERage": "Turn on or off the average function of the Occupied Bandwidth measurement.",
    "[:SENSe]:OBWidth:AVERage:COUNt": "Set the number of averages of the Occupied Bandwidth measurement results.",
    "[:SENSe]:OBWidth:AVERage:COUNt?": "Set the number of averages of the Occupied Bandwidth measurement results.",
    "[:SENSe]:OBWidth:AVERage:TCONtrol": "Set the average mode of the Occupied Bandwidth measurement to exponential or repeat.",
    "[:SENSe]:OBWidth:AVERage:TCONtrol?": "Set the average mode of the Occupied Bandwidth measurement to exponential or repeat.",
    "[:SENSe]:OBWidth:FREQuency:SPAN": "Set the span of the Occupied Bandwidth measurement and the default unit is Hz.",
    "[:SENSe]:OBWidth:FREQuency:SPAN?": "Set the span of the Occupied Bandwidth measurement and the default unit is Hz.",
    "[:SENSe]:OBWidth:MAXHold:STATe": "Turn on or off the Max Hold function of the Occupied Bandwidth measurement.",
    "[:SENSe]:OBWidth:MAXHold:STATe?": "Turn on or off the Max Hold function of the Occupied Bandwidth measurement.",
    "[:SENSe]:OBWidth:PERCent": "Set the percentage of the signal power in the whole frequency span power.",
    "[:SENSe]:OBWidth:PERCent?": "Set the percentage of the signal power in the whole frequency span power.",
    "[:SENSe]:POWer:ARANge": "Adjust the parameters related to the amplitude within the current span range in order to make signal easier to observe.",
    "[:SENSe]:POWer:ASCale": "Adjust the reference level and the scale automatically.",
    "[:SENSe]:POWer:ATUNe": "Search signals within the full frequency range and adjust the frequency and amplitude for optimum display of signals.",
    "[:SENSe]:POWer[:RF]:ATTenuation": "Set the attenuator of the front RF in dB.",
    "[:SENSe]:POWer[:RF]:ATTenuation:AUTO": "Enable or disable the Auto function of the attenuator.",
    "[:SENSe]:POWer[:RF]:ATTenuation:AUTO?": "Enable or disable the Auto function of the attenuator.",
    "[:SENSe]:POWer[:RF]:ATTenuation?": "Set the attenuator of the front RF in dB.",
    "[:SENSe]:POWer[:RF]:GAIN[:STATe]": "Turn on or off the preamplifier.",
    "[:SENSe]:POWer[:RF]:GAIN[:STATe]?": "Turn on or off the preamplifier.",
    "[:SENSe]:POWer[:RF]:MIXer:RANGe[:UPPer]": "Set the maximum power of the input mixer and the default unit is dBm.",
    "[:SENSe]:POWer[:RF]:MIXer:RANGe[:UPPer]?": "Set the maximum power of the input mixer and the default unit is dBm.",
    "[:SENSe]:ROSCillator:SOURce": "Select the internal or external reference source.",
    "[:SENSe]:ROSCillator:SOURce?": "Select the internal or external reference source.",
    "[:SENSe]:STATus:ANALyzer?": "Query the measurement settings of the analyzer.",
    "[:SENSe]:STATus:CORRections?": "Query the correction status.",
    "[:SENSe]:STATus:DEMod?": "Query the setting status of the demodulation.",
    "[:SENSe]:STATus:POWer?": "Query the setting status of the power measurement.",
    "[:SENSe]:STATus:TG?": "Query the setting status of TG (Tracking Generator).",
    "[:SENSe]:SWEep:COUNt": "Specify the number of sweeps in Single sweep mode.",
    "[:SENSe]:SWEep:COUNt:CURRent?": "The query returns the current number of sweeps in Single sweep mode, for example, 8.",
    "[:SENSe]:SWEep:COUNt?": "Specify the number of sweeps in Single sweep mode.",
    "[:SENSe]:SWEep:POINts": "Set the number of points obtained in each sweep.",
    "[:SENSe]:SWEep:POINts?": "Set the number of points obtained in each sweep.",
    "[:SENSe]:SWEep:TIME": "Set the sweep time of the analyzer within the specified span range and the default unit is s.",
    "[:SENSe]:SWEep:TIME:AUTO": "Turn on or off the Auto setting mode of the sweep time.",
    "[:SENSe]:SWEep:TIME:AUTO?": "Turn on or off the Auto setting mode of the sweep time.",
    "[:SENSe]:SWEep:TIME?": "Set the sweep time of the analyzer within the specified span range and the default unit is s.",
    "[:SENSe]:TOI:AVERage:COUNt": "Set the number of averages on the TOI measurement results.",
    "[:SENSe]:TOI:AVERage:COUNt?": "Set the number of averages on the TOI measurement results.",
    "[:SENSe]:TOI:AVERage:TCONtrol": "Set an average mode of the TOI measurement to exponential or repeat.",
    "[:SENSe]:TOI:AVERage:TCONtrol?": "Set an average mode of the TOI measurement to exponential or repeat.",
    "[:SENSe]:TOI:AVERage[:STATe]": "Turn on or off the average function of the TOI measurement.",
    "[:SENSe]:TOI:AVERage[:STATe]?": "Turn on or off the average function of the TOI measurement.",
    "[:SENSe]:TOI:FREQuency:SPAN": "Set the span of the TOI measurement and the default unit is Hz.",
    "[:SENSe]:TOI:FREQuency:SPAN?": "Set the span of the TOI measurement and the default unit is Hz.",
    "[:SENSe]:TPOWer:AVERage:COUNt": "Set the number of averages on the T-Power measurement results.",
    "[:SENSe]:TPOWer:AVERage:COUNt?": "Set the number of averages on the T-Power measurement results.",
    "[:SENSe]:TPOWer:AVERage:TCONtrol": "Set the average mode of the T-Power measurement to exponential or repeat.",
    "[:SENSe]:TPOWer:AVERage:TCONtrol?": "Set the average mode of the T-Power measurement to exponential or repeat.",
    "[:SENSe]:TPOWer:AVERage[:STATe]": "Turn on or off the average function of the Time-domain Power measurement.",
    "[:SENSe]:TPOWer:AVERage[:STATe]?": "Turn on or off the average function of the Time-domain Power measurement.",
    "[:SENSe]:TPOWer:LLIMit": "Set the left limit of the Time-domain Power measurement and the default unit is s.",
    "[:SENSe]:TPOWer:LLIMit?": "Set the left limit of the Time-domain Power measurement and the default unit is s.",
    "[:SENSe]:TPOWer:MODE": "Set the type of the Time-domain Power measurement.",
    "[:SENSe]:TPOWer:MODE?": "Set the type of the Time-domain Power measurement.",
    "[:SENSe]:TPOWer:RLIMit": "Set the right limit of the Time-domain Power measurement and the default unit is s.",
    "[:SENSe]:TPOWer:RLIMit?": "Set the right limit of the Time-domain Power measurement and the default unit is s.",
}
